name = "WeldAndArrow"
version = "0.1.1-dev"
defaultTargets = ["WeldAndArrow"]

[[lean_lib]]
name = "WeldAndArrow"

[[lean_exe]]
name = "glossary_gen"
root = "WeldAndArrow.Gen.Glossary"

[[lean_exe]]
name = "assumptions_gen"
root = "WeldAndArrow.Gen.Assumptions"

[[lean_exe]]
name = "exposition_gen"
root = "WeldAndArrow.Gen.Exposition"

[[lean_exe]]
name = "exposition_generation_full"
root = "WeldAndArrow.Gen.FullExpositionGeneration"
