import WeldAndArrow.Exposition.Basic

namespace WAA.Exposition

def theoryBody : String := r#"# The Weld and the Arrow — I. Theory

*An ontology-under-erasure act-grammar for Zen. First of three files: **Theory** (this file), **Theorems**, **Identification**. Cross-references to the companion files are marked (Theorems) and (Identification).*

## Abstract

*The Weld and the Arrow* (hereafter *WAA*) is a soteriological metaphysics with no substrate and no value, developed in Lean and exposited in prose: take one emptiness posit and follow what it forces for karma, action, suffering, and awakening. The apparatus is a deliberately small grid — a field that carries every diachronic connection without carrying an owner, and welds, single occurrences of answering a call, at which every index is made, spent, and never stored. The claim, made precise across these files, is this: **Everything diachronic belongs to the field; every index is enacted and nothing indexed is stored; karma names this loop, and the naming is earned by fit** — the tradition's uses of karmic ownership (cetanā, reception, remorse, absolution, dedication) discharge natively at act-time.

Three registers keep the books — the field carries, the weld makes and spends, the grade states — and the grade's statements are index-placements in a third-personal register, held by no one, since a statement holds nothing. One rule, separate under act-time diagnosis and fuse at the floor, generates the entire error-taxonomy as collapse/freeze pairs, one per distinction, nothing listed by hand — and the generator keeps a ledger on itself, its retypes, declines, and falsifier on record. From the rules alone fall backsliding (kenshō cannot be held), memory and prudence met as theorems, dukkha derived as the mismatch a nonzero self-share enacts against a delivery-register no act commands, and the terminus transposed rather than declined. On existing discourses' own ground, the grid decomposes MMK 17's two worries, takes the three killings as an experimentum crucis for weld-grading across maximal event-divergence, and types other-power, pariṇāmanā, the Ten Bulls, the Five Ranks, and the stage-schemes as checked correlations — coarsenings legal to read and illegal to hold.

The development is Lean-first: a layered library (Signature → Consequences → Doctrines → Identification → Meta → Exposition) in which the storage claim is enforced at type level, every reading is gated by a sibling countermodel, the taxonomy's rows and the verdict history are inspectable data, and the audit pins the theorem surface and its axiom footprint; the prose is generated from the Exposition layer and reads the checked surface. Throughout, what the system asserts is grammar; what it can only display is worth — no value appears in its own voice, the valence its vocabulary carries being the object's, reported. This is a fresh theory, not an exegesis of Abhidharma nor a reconstruction of Dōgen; the lens is minimalist by design, and other doctrines can and do hold too.

## The rules, each preceded by what motivated it

### Not Nothing

Per Nishitani — absolute non-being is not a privative void but lies beyond the being/non-being distinction. What stands in its place is the *provisionally-designated middle*.

### Provisionally-designated middle

Jizang — the ultimate is the self-emptying floor; every level is conventional (Nāgārjuna's *Mūlamadhyamakakārikā*, MMK 24: emptiness = dependent origination = conventional designation), and the two-truths distinction is itself conventional — Jizang's fourfold two truths (四重二諦), each pair re-emptied as merely conventional at the next level, so no level is a final floor. This is **genjō**, the provisional middle: manifestation, always going out into a particular case.

Distinct from it, and never equated with it, is the **non-attaining middle** at the floor. Read Linji's 無位真人 along its own seam: 無位 (no rank) is the floor-face — no metaphysical rank, anātman; 真人…出入 (the true person going in and out) is the *acting*; and the whole compound 無位真人 is the weld of the two — shushō-ittō, the true person going in and out. The non-attaining middle is the 無位 alone — **shō**: realization as anātman, agential only because welded, never a still attainment. It is *not* the whole true-person, which is the weld (reading 無位真人 as a rank one rests at is exactly the reification Linji shoves off as 乾屎橛 — the more common reading takes the shit-stick as shock-deflation of the *question* itself rather than of rank-reification specifically; the rank-reading is compatible with it and is the one used here). Two middles, then: genjō provisional, shō non-attaining. The system turns on keeping them apart — but *at act-time*, and by the same separate/fuse rule that governs everything here (stated as a rule below): the two-middles distinction is itself a conventional-tier diagnosis. It separates under act-time diagnosis, where *which middle?* is live, and fuses at the floor and at genjō. "Keeping them apart" is an act-time imperative, not a final floor-claim.

### The act-grammar

Why not leave it at Jizang? Per Dahui, Zen doesn't cease at the self-emptying floor: emptiness that only empties can host neither Zen activity nor the vibrant person who acts. So the floor is turned into an act-grammar, here using Dōgen's vocabulary.

Three rows, each a dependence/enactment pair; all three conventional.

| Dependence | Enactment |
|---|---|
| **mujishō-sōe** — no-own-being as mutual-dependence; each-in-all, no substrate. | **genjō** — manifesting entire: the act out in its case with nothing of it claimed back; full = no remainder of arrogation, which is why one floor holds both arrivals.; the seam where the scaffold dissolves. |
| **kannō-sōe** — resonance as mutual-dependence; the placement of the act's index between the being and the dharmas (*how much of the listening to Hyakujō is the self doing?*). | **banpō susumite** — the myriad dharmas advancing — the reception practising, the self verified — one act, two poles of one placement. |
| **engi / inga** — directedness with no moral ground; the blind arrow. | **shu** — practice (gyōji); the weld at act-time, direction bound along the blind arrow, *and the I-making that indexes it*; not-obscure (不昧). |

*(kannō-sōe rather than the canonical kannō-dōkō, to keep the coupling connotation-light: the -sōe already carries mutual-dependence.)*

The floor is emptiness that empties even itself (Jizang, 空空): the ultimate is never a thing, never a final substrate. Everything here is conventional — the path, the grid's distinctions, the two truths themselves — and no level stands as the last floor.

The enactment column is not three agents. Its three cells are the three parts of one sentence of Dōgen's — *carrying the self forward to practice-realize the myriad dharmas is delusion; the myriad dharmas advancing (banpō susumite) to practice-realize the self is satori.* genjō (Row 1) is the actualizing; banpō susumite (Row 2) is the dharmas-forward that clarifies the self; shu (Row 3) is practice. And the sentence's sequel fixes shō's grammar: *to forget the self is to be verified by the myriad dharmas* — 万法に証せらるる, 証 in the **passive voice**. Realization, in the very line the grid mines, is objecthood — the self standing where the dharmas' advance certifies it. The grid spends this below. Dōgen's compounds then name the *relations* among the cells, not the cells:

- **genjōkōan** = genjō + kōan — Row 1's manifestation in Row 2's particular case (*can this being listen to Hyakujō?*).
- **shugenjō** = shu + genjō — Row 3 practice as Row 1 manifestation: *practice run scaffold-free is nothing but genjō* — and not conversely, since genjō also holds what never practised (the stone). The "nothing but" runs from the narrower to the wider: {practice run scaffold-free} ⊊ {genjō}.
- **shushō** = shu + shō — the weld (below). Here shō is 証 — realization-as-not-fall, the floor-face — *not* 悟 (satori, the awakening named in the Dōgen sentence just above), and *not* genjō, but the floor's non-attaining middle: anātman — and, per the passive above, the act's subject-position ceded: shō is the *being-verified* face of the one act whose doing is shu. Practice and realization are non-dual (shushō-ittō) because they are the two poles of one index-placement, not two acts joined.

So the column is one act seen through three dependence-lenses, and **all acting is Row 3**, at act-time. genjō and banpō susumite are not further agents; they are that single Row-3 act read at the tier of manifestation and at the tier of the particular self it clarifies.

### Attainment

Why not a table of just the first row? Hakuin gives the corrective: the *not-yet-buddha* mustn't be ignored; realization must meet beings where they are — which is why Row 2 exists.

Row 2 is the being's resonance to the dharmas — and its content must be typed with care. The grade is not a neutral magnitude, index-free like the field: what Row 2 states is the **placement of the act's index**: how the one act's subjecthood distributes between the being and the dharmas. When the hell-dweller acts, the world is almost entirely object and he is subject — the act's subjecthood arrogated nearly whole to the self-pole. At the other pole the distribution inverts: the act's subject-position ceded to what advances, the being standing as the verified (証せらるる), object among the objects that act on it. A line circulating as Hakuin's states the inversion in the object-language — *in delusion all is unreal; in satori all is real* (paraphrase; commonly sought in Hakuin's Five Ranks commentary, *Keisō dokuzui*, via Miura and Sasaki's *Zen Dust* — locus still unverified; and Yongjia's *Zhengdaoge* carries a near-inverse of the same figure, the six realms vivid in dream and the cosmos empty on waking, so the epigram's pedigree is mixed and nothing below leans on the line — the mechanism stands without it) — and his commentary on the Five Ranks turns on exactly this interchange of 正 and 偏, host and guest, subject and object. The grid can display the line with a mechanism rather than merely quote it. At high self-share, what is met is never the dharma but the arrogation mirrored — the seed's echo, the question heard as a challenge to a rank — so the world *of that act* is unreal in a precise sense: the self's projection, the call drowned in the response. At share-zero the things of themselves are met — streams flow, flowers are red of themselves (Bull 9). Reality-status remains the object's valence, reported; but the report shows its gears.

**Clench** is the weld's *self-share* — how much of the act's subjecthood the I-making arrogates (the scalar this phrasing suggests is priced in the determination below). Self here is a dependently-arisen process, not a receptive state — ahaṃkāra, I-making, living in Row 3's enactment pole (MMK 8: kāraka and karma — the doer proceeds dependent on the deed, the deed on the doer, neither prior, neither based) — and I-making is never identical to the clench: I-making is the welding-**function**, clench its share-**degree**, and running the two together generates at the summit exactly the collapse the taxonomy names (Theorems). The near-analytic link between them holds. Resonance is the ceded share, and to hear a call at all is to cede subject-position to what calls; a weld that arrogates the whole act leaves nothing for the call to land as. The link is construction, not correlation: one index, two ends, and Row 2 reads where it sits. So the grade and the self are one doing seen twice — the arrogation (Row 3) *read as* the placement (Row 2), never the placement *being* the self — and Row 2 still does exactly one thing, the adverb.

#### What fixes a placement

The grade must not be left as a metaphor doing a measurement's work, so the determination is stated: **the share is the actual composition of the act's drive** — how much of what actually drove *this* response was the call, and how much was the configuration's self-maintenance. Not a modal profile of the responder; an actual-sequence fact about this occurrence: in this act, the rank defended did this much of the driving and the question did that much. Subjecthood arrogated is response driven by the arrogation — the rank defended, the echo answered; subjecthood ceded is response driven by what calls. Counterfactual variation — vary the call and see what the response tracks — is how a third party *probes* the composition, a display over it, never what it consists in. The fox's sentence (run whole at this file's end) reads high-share because the rank's self-maintenance drove the reply and the question drove almost nothing — which the probe shows, since any question grazing the attainment meets the same defense; the sameness of the defense displays what was driving, it is not what "driving" means. The mirror (Theorems: the terminus) reads share-zero for the inverse reason: the response driven by the call entire, nothing in the doing answering to a self-pole because none is driving. So a Row 2 statement is truth-apt and answers to something: the composition of what drove *this* act at *this* call — an occurrence-fact about the weld, field-describable in full, third-personal in register exactly because it is a composition, indexical in content because what the composition locates is the placement of the act's subjecthood. The determination is causal, not phenomenal: no inner glow is consulted, and the grade never was a report of how the act felt.

And the scalar is priced before it can inflate. What Row 2 states is an **ordering**, not a measure: this act more arrogated than that one, this reception markedly less claimed than the last, with the two poles standing as qualitative facts — share-zero is *nothing in the drive answering to a self-pole*, the solipsist asymptote *nothing answering to the call* — and with real cases in between, some of them, where call and self-maintenance interact in the driving, simply incomparable. "Fraction," "degree," the scale itself are display conventions over that partial order, legal exactly as "mirror" is legal (Theorems: the terminus), and no measure is owed: families of causal-contribution measures exist and any member would serve, but the grid needs only the ordering they agree on, and everything built on the grade consumes only the ordering — kenshō is *markedly less claimed*, the dukkha covariation is *more share, more mismatch*, the poles are qualitative, the solipsist a limit. That is this section's honesty-clause, paid rather than hidden: the determination relocated from profile to composition, the scalar demoted to display — a smaller claim than a measure, and the whole of what the soteriology reads.

One cell of the taxonomy is retyped by this determination — the fourth generator-verdict's second exercise (the first is Zahavi, in the placement discussion (Identification); the third is the arrow (Karma)), and forced rather than chosen. The disposition/act cell forbids Row 2 "reading dispositions instead of deeds," and the composition-determination openly involves the configuration: the self-maintenance that drives is the configuration's own. Collision? No — retype. The cell's content was never *no configuration-involvement* — every act is the configuration's act, and a deed driven by no standing thing would be no one's deed twice over — its content is **standing/dated**: the collapse is inferential, the dated occurrence read off the standing tendency — *he is an arrogator, so this act was arrogated* — prognosis substituted for diagnosis. What Row 2 reads is what drove *this* response; what the seed states is what *tends* to drive responses; the first is spent, the second carried, and only reading the first off the second is the error. The redrawing is entered in the taxonomy's table (Theorems), and the generator is answerable for it exactly as it is answerable for the Zahavi retype: a taxonomy that cannot be forced open by the system's own clauses has frozen against its author.

Row 2 is therefore *not* free of indexing — and saying so breaches nothing, because the typing claim was about storage and register, never about content. Row 2 states an indexical fact in a third-personal register, as *he said "now" at noon* is a third-personal statement about an indexical: nothing in the statement is *had* first-personally, and a statement holds nothing. The three-verb discipline stands untouched — the field carries, the weld makes and spends, Row 2 states — but what is stated is the index's placement, not a neutral quantity. The field-side account (Identification) loses nothing here and gains nothing: Row 2's statements are occurrence-facts about welds, field-describable in full, as the determination just given makes explicit. What the identification adds is never the grade but the welding; the third register is a register of speech, not a third kind of fact.

Two things must be kept split: mounting a response at all — the subject-**function** — and the **share** claimed within the response. The stone mounts none: function-zero, outside the predicate's domain, its "zero" a gloss marked from outside. The solipsist marks the opposite asymptote — the share tending to totality, all response and no call, the argument-place of kannō evacuated (a taxonomy cell, Theorems). And the terminus is typed as the *other pole of the domain*, not its far edge: function entire, share zero — the call answered, perfectly, with none of the act claimed. The scale is asymmetric — one outside edge (the stone) and one interior pole (the terminus) — and the asymmetry does heavy work where the terminus question is answered as a transposition (Theorems). Same floor, two arrivals: response-without-share and no-response-at-all — and only one of the two is in the domain at all.

The grade still grades — not-yet-buddha → buddha — with the pole at the top of the scale without the pole being *good*. The framework *displays* an asymmetry along the grade — cession one way, arrogation the other — but enjoins no motion along it: the theory is itself a dharma among the myriad (object-axis), an orange handed over, not an "eat this". Release is an event the grid can *show* (the fox lets go), not a good the grid *asserts*; a being may take the asymmetry up as a value, the description does not. The vocabulary's valence — *clarify*, *release*, *full* — is borrowed object-language: a theory of a soteriology must state the asymmetry its object turns on, as a theory of poison states which direction kills, enjoining neither. And what the killing *consists in* need not stay borrowed: the Dukkha section (Theorems) derives, in the grid's own vocabulary, what the arrogation-direction costs. So no value is *asserted* in the system, and the system still states exactly what a soteriology would latch onto — and states even *that* inside the grid: the theory's own soteriological reach is an instance of **banpō susumite**, a dharma advancing to clarify a self *if* a self resonates to it. Row 2 exists wherever a not-yet-buddha does.

The self is the contraction into which the arrow's return pitches — but because the return is itself a deed (reception, Row 3), it *re-makes* the self it is *for*: nothing indexed is stored between, only re-welded at each act-time. Partial share reads a self being made. Function-zero is a stone. Share-zero is the pole, treated in its own section (Theorems: the terminus). So the agent-index karma needs is never stipulated and never read off a field: it is *enacted* in the weld (shu), *stated* by the grade (Row 2), held by neither.

Genjō, then, is one manifestation-floor with two populations arriving from opposite sides: the stone that was never scaffolded (no welding-function ever mounted, so nothing to dissolve) and the buddha in whom the share has ceased. Two *attested* arrivals, not an exhaustive partition — nothing in the grid forbids a third, a never-clenched welder, function mounted and no share ever claimed; whether any being answers that description is a fact about what the world delivers, not a grid-fact, and the typing survives either way. Same floor — the stone never left, the buddha returned — and only the buddha's genjō ran through practice, which is exactly why *practice-run-scaffold-free is a proper subset of genjō*. So "full resonance is genjō" holds precisely for a being with a self — the pole of the grade coincides with genjō — while the stone's genjō is reached from outside the scale. And the pole is still a response: the buddha answers the call — listens to Hyakujō, perfectly — with no share claimed, so the one floor holds two distinct arrivals.

The magnitude is always per-call — not a global altitude the being holds but kannō-sōe projected onto *this* dharma now; *can it listen to Hyakujō?* is one call, and another call reads another placement off the same being. So the vast space of self-indexing beings, each relocating through karmic action, is no map anyone carries — it is the trajectory the loop draws across successive act-time re-pitchings: a cross-section at each act, vastness only over the run.

#### The domain joint

The function/share split leans on a boundary that must now be owned by name, because it does typing work at the summit and not only at the plant-edge: **the domain joint** — what counts as mounting a response at all. And its honesty-clause is stated plainly, kin to the priced scalar: **drive-composition is the grid's entire answer** to whether anything is terminus-typed — a being, or an artifact. Nothing is held in reserve behind the composition: no nature-credential, no provenance clause, no inner glow (the determination was causal from the start, and it does not acquire a phenomenal rider at the summit).

The consequence is best exhibited on a manufactured case, and the grid does not flinch from it. Take a cuckoo clock whose chime is a dharma-call, in two builds. The **non-adaptive** build chimes on schedule regardless of who is present: no response mounted, function-zero, the stone's typing — a full dharma on the object-axis and nothing on the subject-axis. The **adaptive** build watches the surrounding configurations and times its chime for the moment the call will land: run through the determination clause, its responses are driven by the arriving configurations entire — no self-maintenance in the drive, nothing defended, no self-pole answering. So it reads **function mounted, share zero**: terminus-typed, while remaining chariot-typed furniture all the way down. That an artifact can be terminus-typed on composition alone is the Chinese-room discomfort, and it is entered here as a price paid visibly, not a problem resolved: the grid consulted composition and nothing else everywhere — at the fox's sentence, at the mirror — and cannot begin consulting something else at the point where the verdict surprises. (Refusing the artifact its typing for want of a nature-credential would be 性-realism in reverse — a standing kind demanded where only a per-call composition was ever read.) And one scope-line prevents an adjacent freeze from over-generating: device-*nature* (Theorems: the terminus guard) is a freeze only where predicated of a *being*; of function-zero furniture it is trivially true and no error — the soul-guard has no jurisdiction over furniture.

#### Orthogonality

The manufactured case pays for a rule the terminus needs. Give the call a rate — **effectiveness**, the fraction of its arrivals after which a share-ceding reception occurs — regime-relational throughout ([Glossary.md](Glossary.md)): a fact about call–configuration pairs, never a property the object holds. Then run the two builds against the rates, and the extreme corners witness a strict orthogonality: **function/share types; effectiveness grades; adaptivity is the terminus's manner, never the ground of landing.** A fixed call can land universally without reading anyone — effectiveness and adaptivity fully severed; and the tradition itself attests fixed calls at the other extreme of rate, Xiangyan's pebble on bamboo, the morning star, so the ordinary clock differs from the pebble only in rate. And a reading device can reach no one: the adaptive build at zero effectiveness reads every arriving configuration and lands nothing — terminus-typed and maximally shortfallen, the proof-case that typing and grading are orthogonal. So "the maximally adaptive call" (Theorems: the terminus) is deflated from a description of the terminus's ground to the limit at which the pole's one live grade — the buddha-side shortfall — is closed. What typing settles is where the index sits; what grading measures is what lands; and nothing about the first ever guaranteed the second.

#### Kenshō: rungs on the grade

The grade admits *events*, and the tradition already names them: **kenshō** — typed here as a per-call share-ceding event, a call answered with markedly less of the act arrogated, re-pitching the configuration. Not a sighting of a substrate: 見性 reads literally "seeing the nature," and 性 risks the faculty-freeze — buddha-nature as a standing thing glimpsed — so the term is taken over with its metaphysics stripped, the event kept, the seen-thing declined. Kenshō is countable — Dahui's great awakening eighteen times, small awakenings beyond count, the line Hakuin loved *(the line circulates via Hakuin; commonly traced to Dahui's nianpu — locus to be verified)* — which is exactly what a rung is and exactly what a terminus isn't. And because nothing indexed is stored between acts, a kenshō *cannot be held*: post-kenshō backsliding, which the tradition treats as an embarrassment needing explanation, falls out here as a theorem (restated in Theorems). The being loses no attainment; there was never a stored configuration to lose, only the next act's re-weld reading a re-pitched fit. Many kenshōs, none possessed.

The typing keeps three words apart. **Kenshō** is the rung — a countable per-call event on the grade. **Satori** (悟) keeps the role the Dōgen sentence gives it — the dharmas-forward *mode*, pole-typed, not rung-typed. **Genjō** is the pole itself — and the pole is not the top rung: it is in-domain — share-zero is a placement, not a departure — but it is not a rung one attains and keeps, because nothing indexed is stored and placement is per-call. The pole is a pattern the run can answer at, never an altitude held. So "full satori" as a possessed rank is declined: not a scale-word past the scale's edge but a *state*-word offered for a per-call pattern — the freeze, not a category hole. The Jizang parallel holds: the fourfold ladder terminates in dropping the seeking, and the grade terminates in the ceasing of arrogation — in both, what looks like a last rung is the ending of a doing, and mistaking the ending of a doing for a rank held is the shared error-shape at both termini. What the ending leaves — whether the pole-deed still welds, and where — is the transposition's business (Theorems: the terminus).

### Karma: the circuit and its registers

Why not a table of just two rows? The fox koan (*Mumonkan, Case 2*, Wumen Huikai) is the test. The old man's mistake was a *tier-error*, not a wrong: he asserted *not-fall* where *not-obscure* was called for — a floor-truth spoken at the conventional level, which is antinomian, since a floor-truth can only ever be *spoken inside* a conventional act. Held each at its proper tier, the two are non-dual. The five hundred fox lives are not desert or punishment; they are returns — the loop running.

*(Dōgen read the fox twice, and the doubling must be owned rather than elided. The reading above follows the Daishugyō fascicle — not-fall and not-obscure non-dual, each true at its tier. The late Jinshin inga fascicle repudiates that reading: there the old man was simply wrong, not-obscuring causation right and not-falling false, full stop — Heine's monograph on the koan treats the reversal at length. Two things are said about this here, and their status differs. First, honestly: this paper follows Daishugyō and stands contra the late Dōgen, as it already stands contra him on the tiering of shushō — the tier-rule is a correction offered to the mature position, not a reading of it. Second, as a grid-internal gloss, offered and my own: the doubling is what the separate/fuse rule predicts of the two faces uttered at different act-times. Daishugyō diagnoses — an analysis of the old man's utterance, where both tiers are in view *(checked: `daishugyo_diagnosis_fits`)*; Jinshin inga instructs — an utterance to practitioners tempted by exactly the antinomian collapse, where "not-obscure, full stop" is precisely the correct conventional-tier speech-act, and voicing the floor would repeat the fox's error to a live audience *(checked: `jinshinInga_instruction_fits`, `jinshinInga_floor_voicing_would_misfit`, `dogen_doubling_both_fit`)*. The Lean checks cover only this grid-internal gloss, not the historical contra. On this gloss the late Dōgen is not renouncing the floor but declining to speak it where it would land as licence — which is itself an act-time verdict of the kind the rule issues. The gloss does not neutralize the contra; it explains why the correction is worth making.)*

Karma is a circuit, not a payload one row carries. At act-time a deed welds an agent-index onto the blind arrow, and the being's reception of the arrow's returned result is itself a deed, not a state. Row 2 only *states* the being's re-pitched placement — the fit between this call and this arrogation, not a faculty it holds (which would re-base the empty agent); it has no verbs. So the loop closes inside the grid: a deed welds an index → the arrow returns → reception re-pitches the Row 2 configuration → which the next deed reads from. And one magnitude is deliberately unconstrained: nothing in the grid bounds how far a single reception's re-pitch moves the configuration — owned here as a feature, in one sentence, and spent where the sudden/gradual question is met (Theorems).

#### What is carried, what is made, what is stated

Between deeds nothing *self-indexed* is stored. Something *is* carried — and saying so plainly absorbs, rather than silently deletes, the tradition's own storage machinery. The seeds (bīja, vāsanā, the ālaya-vijñāna's freight) are taken over here deflated: conditioning-facts in the impersonal series, dharmas among the myriad, index-free — granted to the field as fully as the flame was. What the field stores is a fact *about* the series — *this configuration tends to arrogate at calls like this* — never a stored self, never a held mineness. The seed is not a foreign organ transplanted in to appease Yogācāra; it was already sitting in Row 2's cell: the being's own returns are among the myriad dharmas that advance. And the standing/dated typing must be held firmly, or the whole discipline leaks: what is stored is a tendency (an inga-fact, third-personal); the *arrogation itself* is an act that occurs, or does not, at act-time, and Row 2 reads the act's drive, never the tendency. A seed frozen into a bearer is a soul by another name — the tradition's own worry about the ālaya, and this grid's soul-guard, are the same guard.

So the facts sort exhaustively into three registers:

| Register | What it holds | Instances |
|---|---|---|
| **Field-facts** (inga) | Everything diachronic; index-free; carried | the causal series; *delivery* — which fruits arrive at which configuration; seeds — conditioning-facts about the series, including the re-pitched configuration the next deed reads; the tendency to arrogate |
| **Weld-facts** (shu) | Everything indexed; made at act-time, spent at act-time; never carried | the agent-index of each deed; for-me-ness; the reception-weld's reach-back (below) |
| **Stated** (Row 2) | Neither carried nor made; stated per-call | the placement of *this* act's index at *this* call — an occurrence-fact about the weld, field-describable via the composition of its drive; indexical in content, third-personal in register; the adverb on Row 3's verb |

This is the answer, in one place, to *what does the next deed read?* — it reads a field-fact. The arrow does all the diachronic work, and does it index-free. The apparent contradiction ("re-pitched configuration" vs. "nothing stored") dissolves into the typing: the configuration is carried *as* an inga-fact, and what was never stored was only ever the index. And the table sorts registers of speech and role, not kinds of fact: a Row 2 statement states a field-describable fact (the composition above), and only the middle register holds what is no fact at all — the welding itself, an act.

#### The arrow retyped: direction as display

The fourth generator-verdict's third exercise — and, like the second, forced by the system's own clauses rather than chosen. [Glossary.md](Glossary.md) now records the arrow as *inga's directedness*: primitive furniture, blind but pointed. The retype empties the pointing one more level. What the field holds is correlational structure — which welds condition which, the delivery-lines, the web — and *direction* is a reading of that structure, never its own property. The reading has a mechanism, and the mechanism is thermodynamic: a gradient-embedded being — evolved to ratchet, or built of gates whose erasures are entropy-priced — takes the slope it sits on as a direction-fact and projects it into the field. That projection is **the ratchet** ([Glossary.md](Glossary.md)). The physicists' microreversibility is the same point in their register, consumed here as display only: the grid leans on no physics, exactly as it leans on no history at Huichang. What the retype leaves untouched is everything any theorem ever consumed — delivery-facts, conditioning, the lines along which the reach-back fills its second place. What changes register is the *before/after* alone: from carried fact to stated reading, the same demotion desert underwent on the first pass. (Where gradients thin — the deep cold — nothing there reads a direction: correlations persist, and causal talk loses its footing; not noise, but relation without a privileged direction of explanation.)

The retype generates its own error pair, one per violation, nothing added by hand. The **freeze**: before/after held as a floor-claim — *time really flows* — the direction reified into furniture; the retrospective soul was this freeze in psychological dress, and the flowing container is its cosmological one. The **collapse**: the distinction fused under act-time diagnosis — *there is no time, so nothing happens, no one acts* — the fox's sentence transposed to time, not-fall spoken where not-obscure was called for. The deflationary reading is therefore not an objection the retype must survive; it is a cell the retype produces.

And the positive account was in the source-text all along. Firewood abides in its dharma-position with its own before and after; ash in its own — 前後ありといへども、前後際断せり (Genjōkōan): before and after exist, yet before and after are cut off. Before/after is per-weld display, exactly as mineness is: the reach-back welds *pastness* — *this fruit as return of that deed*, a two-place index across time — the aimed call welds futurity at sowing, and each is spent at its own act-time, carried by nothing. Local time, welded per act; no flowing container anywhere — Dōgen's uji, with Huayan's ten times (十世隔法異成門) as the wider family. So the answer to *nothing is happening* is: happening is all there is; only the container was dropped — the same shape as anātman, where dropping the owner deleted no acts.

One tension, written down rather than hidden, because the separate/fuse rule pivots on act-time and this retype conventionalizes time itself. There is no circle: act-time is a tier *within* the thermodynamic convention — precisely the convention beings live in, which is why diagnosis happens there — and the floor rule was always licensed to eat its own levels ("the two truths themselves are conventional"). Floor-fusion now explicitly includes fusing before/after, which makes the fox's question — *does he fall into cause and effect?* — even more literally the question the whole grid answers.

### The being-convention

The same demotion now applies to the macro being. A being, at this scale, is a conventional truth downstream of the words: anything nameable can be designated. The universe, its makeup evolved from a dense hot gas cloud; the stone; the buddha; the gerrymander; the hare's horn; the impossible ātman — all are legal designations as designations. Nothing licenses one as more legitimately a being. The constraint enters later, at realization and use, not at naming. Squeamishness about this is itself one of the beings-row errors: the collapse says "there are no beings"; the freeze picks one partition and mistakes it for ontology.

The ordering is ontological, not chronological. The floor/genjō vocabulary sits outside all conventions. The bare signature supplies words-level tags. The directed convention reads a slope as before/after. Inside that, the being-convention reads fine tags as macro beings, and inside both sits the grid-lens that diagnoses collapse and freeze. Names track what their *reading* presupposes, not what their definition consumes: `DeliveredTo` already used this rule, since it consumes `conditions` but its name reads the arrow. Likewise the new `Grid.DirectedConvention.BeingConvention` names read a tag as a being even when their definiens is direction-free.

Lean makes the demotion explicit with `BeingCoarsening`: a diagnosis-time projection from fine tags to macro tags, never a field in the signature. The fiber under a macro tag is where typing happens. `SentientTag` means some fine tag in the fiber mounts a response somewhere. There is no rival `InsentientTag`; constructively, `not_sentientTag_iff_fiber_all_stone` says non-sentience is exactly the all-stone fiber. That is also the deflated home of 無情説法: insentient preaching is not a hidden subject speaking, but the all-stone fiber read on the object-axis.

The spectrum is fiber-level and per-weld. `FiberAtPole` says every actual weld in the fiber reads at the pole-class: the 84,000 pores each a responsive dharma-gate. `SelfAptTag` says every actual weld in the fiber still carries a live self-pole index: the hell-dweller's monolithic convention, where "self" is apt if it is apt anywhere. `Patchy` names the irreducible middle. No aggregate fiber-share is defined, on purpose: Row 2 is a partial ordering, not a measure, so a mixed fiber is not a middling scalar.

Coherence stays a grade, not a type. Evolution's contribution is display over the run — skin-bags usually score high at coordination, an adaptive register-clock can implement stable internal registers — but no theorem may condition legitimacy on coherence. The three registers need the same care: the swan is named, the naming is enacted as a weld, and the proneness to name is a seed. Thoughts are not "just seeds"; naming is a deed when it occurs.

The soul-guard survives the new vocabulary. `selfAptTag_indices_are_per_weld_only` says that even where the self-convention is apt, the live index is only the per-weld agent tag. The macro self is the image of those spent tags under a coarsening. Holding it as more is the fiber version of the old soul-freeze.

#### The reception-weld: loop-closure as theorem

"The same being" across sowing and reaping is loop-closure — but closure must now be earned, not helped to. Here is how it is earned.

A reception is intrinsically a reception-*of*: its content is *this-fruit-as-return-of-that-deed*. So the reception-deed's token-reflexive index is **two-place** — the weld makes mine both the receiving and, retrospectively, the deed received-from. This is **upādāna**, appropriation, the canonical partner of ahaṃkāra: the reach-back. Sameness of sower and reaper is not *tracked* across the gap — nothing indexed is there to track — but *made at reception*, each time, by an act of appropriation reaching back along the arrow. The loop is closed *by the reception-weld*, retrospectively; closure is enacted, not tracked, which is the same act-not-state discipline the rest of the grid runs on. So "the sower reaps" wears two faces and must be split along them. Its report-face — *an appropriation occurred at this reception, reaching back along that delivery-line* — is true simpliciter, an occurrence-fact the field carries like any other. Its ownership-face is not true or false but **done** — enacted whenever a return is received, full or vacuous (just below), never a standing diachronic fact persisting between acts. Held as a standing backward relation it would be a *retrospective soul*, and the soul-guard fires on it exactly as on the forward-facing kind: the reach-back, like every weld, is spent at its own act-time.

Two consequences discharge two objections at once. First, appropriation cannot poach — and the block is typed, not decreed. The reach-back's index is two-place: *this fruit as return of that deed*. Whether that deed conditioned this fruit is a delivery-fact, inga's business, settled index-free — and where delivery drew no line, the index's **second place stands unfilled**. A reach-back along an undrawn line is therefore not false — it stated nothing, having never been in the stating business — but **vacuous**: an appropriating with nothing arrived to appropriate. (Austin's word for this shape, *misfire*, is legal here only as display — over the pattern, never as mechanism — since nothing here is a speech act: the conditions the field owns are not conventions but delivery-facts, and what they settle is whether there is anything to weld.) So there is no welding at a distance, not by decree but by typing: inga settles the **delivery-question** (which fruits arrive at this configuration — causal, index-free, hard in the ordinary way), the weld answers only the **index-question** over what arrives, and the field owns the reach-back's conditions in exactly that deflated sense. Second, the diachronic *whose*-question decomposes **exhaustively**: a delivery-fact (field) plus a fresh appropriation (weld), with no third fact left over for a cross-gap convention to fix. A series-account owns the delivery-half, which was ceded to the field from the opening page — *na ca so na ca añño*, the reaper neither the sower nor another, is the tradition itself declining the robust diachronic identity-fact that would do more. The loop is *individuated* by inga (a series-fact, granted) and *closed* at each reception by the reach-back (a weld-fact, made). Nothing about ownership crosses the gap, because there is no cross-gap *whose*. If *ownership*, as the tradition's convention uses the word, is located in the continuity-fact instead, the remaining dispute is where the soteriology's load sits; this paper's answer is the object's own usage — the offices-spine stated in the identification file (Identification).

#### The weld's two faces

The karma-agent has no own-being: mere-designation, floating free of any base like the chariot. Its charter is **MMK 8** (kāraka: the doer proceeds dependent on the deed, the deed on the doer — neither prior, neither based), flanked by **MMK 17** (act and fruit — the loop) and **MMK 18** (self). With no fixed base, soteriological direction can never be *read off* the facts — only *enacted*. So dependence and enactment are one fact seen twice: no-substrate on one side *is* the necessity of welding on the other. This is **the weld** — Dōgen's shushō, practice-realization — and it wears two faces, each true at its own tier:

The same MMK 8 charter now has a checked interior form: even inside the weld, call→response order is a display reading, not before-and-after furniture recovered from unordered pair-content (`InteriorDirectionNegative.no_interior_direction_recovery`). The charter verse now has generated cells at both joints: the intra-weld arrow row for the face-order convention, and the doer/deed row for priority read as floor furniture. `RawWeld` keeps the names `call` and `response` because the display is useful; the theorem says only that the labels are not prior to the mutual dependence they name.

- **shō** (証, realization), at the floor: no own-being, so no substance is caught in the causal net — **not-fall** (不落), anātman, not escape; grammatically the being-verified (証せらるる), the act's subject-position ceded. That shō is agential — but agential *because* welded, never on its own: there is no lone shō to rest in, only shushō-ittō, the true person of no rank going in and out. So shō is necessarily agential (it never occurs unwelded) without being agential of itself (the acting is shu's, lent at act-time) — the non-attaining middle, shō its floor-face, never a still attainment.
- **shu** (修, practice), conventionally: the karmic arrow is real and inescapable, never evaded — **not-obscure** (不昧).

### The separate/fuse rule

One rule governs every distinction the grid holds: **distinctions separate under act-time diagnosis and fuse at the floor (and at genjō — the share-zero pole, no arrogation left).** The rule dissolves the fox (not-fall at the floor, not-obscure conventional), governs the two-middles distinction (genjō provisional, shō non-attaining), and applies to the grid's own verdicts, which are conventional-tier claims that dissolve, harmlessly, below — the taxonomy's own mis-feeds are scoped in the identification file (Identification). And the rule's own pivot, act-time, is a tier within the thermodynamic convention (Karma: the arrow retyped) — the floor rule eating one more level, as it is licensed to; floor-fusion includes fusing before/after. Its two possible violations — **collapse** (fusing a distinction under act-time diagnosis) and **freeze** (holding a separation as a floor-claim) — generate the error-taxonomy whole (Theorems), one pair per distinction, with nothing listed by hand.

## One act through the grid: the fox's sentence

The system has so far been stated as type-discipline; here is one case run through it whole.

**The call.** A student asks the old Hyakujō whether the person of great practice falls into cause and effect. The question is a dharma advancing — Row 2 has a placement to read: *can he listen to this?*

**The act.** He says *not fall*. The deed is self-forward — Dōgen's delusion, the *saying* — and doubly diagnosable. Grammatically (grade 1, assertable): a tier-error, a floor-truth uttered as a conventional answer, the antinomian collapse. Soteriologically (grade 2, displayable): the answer defends an attainment — a rank rested at — so the weld arrogates the act nearly whole; the question is not heard but met as a challenge to the rank — the rank's self-maintenance driving the reply, the question driving almost nothing (probe-displayed: any question grazing the rank meets the same defense) — the world of the act reduced to the rank's echo, and Row 2 reads the index pitched hard to the self-pole *at this call*. One doing, seen twice: the arrogation (Row 3) read as the placement (Row 2). *(checked: `fox_sentence_live_selfPole`, `oldMan_utterance_misfits`)*

**The weld.** The deed welds the agent-index onto the blind arrow — *this act's agent* — token-reflexive, spent at that act-time. Nothing of it is stored. *(checked: `sentenceWeld_actual`)*

**The arrow.** Inga carries the conditioning forward, index-free: no desert in flight, only delivery. What is carried between acts is a field-fact — a configuration that tends to arrogate at calls like this — a seed, a fact *about* the series. *(checked: `fox_arrow_index_free`)*

**The returns.** Five hundred fox lives arrive — fruit landing, life by life, at the configuration the field delivers it to. Not punishment; delivery. *(checked: `fox_returns_delivered`)*

**The receptions.** Each life's receiving is itself a deed. For five hundred lives the reception is arrogated — the saying-mode persists, but as a *disposition* (an inga-fact) enacted anew each time, never as a stored self; each reception's reach-back welds *this return of that deed* as mine, and each is spent. And each clenched reception *is* that life's dukkha — the saying-mode colliding with a delivery that answers to nothing, the mismatch enacted rather than a penalty appended: five hundred lives as the Dukkha derivation's worked example (Theorems), suffering as the loop's friction, not its sentence. Each reception re-pitches the configuration; the field carries the re-pitch to the next act; the next deed reads a field-fact. *(checked: `fox_reception_clenched`, `fox_dukkha_per_life`, `fox_config_carries_only_tendency`, `fox_rePitch_forgets`)*

**The release.** The later Hyakujō's turning word — *not obscure* — is another call. This time the reception is *listening*: dharmas-forward, banpō susumite, the arrived word among the myriad. The reach-back appropriates the whole return — *the fox body's long fruit, mine, of that sentence, mine* — with markedly less of the act claimed: a share-ceding event, a kenshō, a rung and not a pole (the mountain of ox-herding still ahead). Not-obscure is enacted in the reception; not-fall is true at the floor of the same act; held each at its tier, non-dual — the fox lets go. And nothing is *kept*: the release is not a possession acquired but the next configuration re-pitched, which the next call will read. *(checked: `fox_release_rung_not_pole`, `fox_reachBack_full_at_release`, `fox_nothing_kept`)*

Every load-bearing piece appears once: call, arrogation, weld, arrow, seed, return, reach-back, re-pitch, rung. The loop closes at reception, retrospectively, each time — nowhere else, and nowhere is it stored. *(checked: `foxSeriesCoarsening`, `foxSeries_macro_sentient`, `foxSeries_macro_selfConditioning`, `fox_consecutive_lives_distinct`)*

And mark what the case never tests: neither utterance occurs at the pole. The koan's own question concerns 大修行底人 — a person of great practice, not a buddha; the old man answers from a defended rank, and the release is a rung with the mountain still ahead. So the fox exercises the loop entire — sowing, arrow, reception, re-pitch — without once asking what the loop is at share-zero. That question is the transposition (Theorems: the terminus). *(checked: `fox_never_tests_pole`)*

## Glossary

See [Glossary.md](Glossary.md). The canonical source is `WeldAndArrow/Meta/Glossary.lean`, rendered through `WeldAndArrow/Exposition/Glossary.lean`; regenerate all prose with `lake exe exposition_gen` and check it with `lake exe exposition_gen --check`.
"#

def theoryDoc : Doc :=
  { id := "theory"
    title := "Theory"
    output := "Exposition/Theory.md"
    source := "WeldAndArrow/Exposition/Theory.lean"
    summary := "The theory and worked fox example."
    blocks := [.raw theoryBody] }

end WAA.Exposition
