/-
================================================================================
  WeldAndArrow.Consequences.Taxonomy
  Error taxonomy, table order, and witnesses
================================================================================

Reading and motivation: Identification/Commentary.lean, C.2.
-/

import WeldAndArrow.Consequences.Basic

namespace WAA

namespace Grid

variable {Designatum Contrib : Type} [PreorderBot Contrib]
variable (G : CoreReadings Designatum Contrib)

namespace DirectedConvention
namespace BeingConvention
namespace GridConvention

/- The lens's own vocabulary: the innermost convention. The abstract
   `ClaimLanguage` machinery remains at `Grid` level; this namespace supplies
   the concrete rows generated from it. -/

/-- The nested conventions as objects the lens can diagnose claims about. -/
inductive ConventionLayer
  | directedTime
  | intraWeldArrow
  | beings
  | gridLens
  | weldGrain

/-- Claims for convention-layer rows. `conventionLive l` says the layer's
    distinction is in force; `layerDenied l` is the deflation. -/
inductive LayerClaim
  | conventionLive (l : ConventionLayer)
  | layerDenied (l : ConventionLayer)

/-- Every schema-generated row of the Grade-1 table, as inspectable data. The
    three convention layers embed via `layer`; the level-n row is generated by
    `ladder` instead. -/
inductive RowTag
  | layer (l : ConventionLayer)
  | foxWeld
  | rungPole
  | doerDeed
  | functionShare
  | karmaInga
  | sowingReaping
  | deliveryIndex
  | weldEventType
  | standingDated
  | subjectObjectAxis
  | standingSentience
  | perCallGlobal
  | terminusExit
  | selfPoleTransposed

/-- The two sides of a schema-generated row. `inForce r` is the conventional
    side; `denied r` is the floor-side deflation offered as diagnosis. -/
inductive RowClaim
  | inForce (r : RowTag)
  | denied (r : RowTag)

/-- Floor-apophatic semantics. At `floor` no claim holds: the floor asserts
    nothing, and fusion there is degeneracy of the claim-space, not joint
    truth. At act-time the conventional side holds; the denial side holds
    exactly at the pole-class, where it is earned as diagnosis (不昧). Nothing
    in this language affirms a positive truth predicate of the floor. -/
def rowLanguage (G : CoreReadings Designatum Contrib) : ClaimLanguage G where
  Claim := RowClaim
  Holds
    | .floor, _ => False
    | .actTime _, .inForce _ => True
    | .actTime w, .denied _ => AtBot (G.share w)

/-- Nothing is assertable at the floor; the ultimate appears in the formal
    language only as the point where the language runs out. -/
theorem no_row_claim_holds_at_floor :
    ∀ p : RowClaim, ¬ (rowLanguage G).Holds Tier.floor p := by
  intro _p h
  exact h

/-- At the floor every distinction of this language degenerates. Fusion is by
    silence, not by joint truth; compare `not_freeze_of_same_claim`. -/
theorem floor_claims_indiscernible :
    ∀ p q : RowClaim,
      ((rowLanguage G).Holds Tier.floor p ↔
        (rowLanguage G).Holds Tier.floor q) := by
  intro _p _q
  exact Iff.rfl

/-- Without relying on the conventional, nothing is taught: any recorded
    utterance that fits its offered tier is offered at an act-time tier. Error,
    and therefore correction, exists only under separation (MMK 24.10). -/
theorem fitting_offer_is_actTime
    (u : RecordedUtterance G (rowLanguage G))
    (hfit : u.FitsOfferedTier) :
    ∃ w : G.Weld, u.offeredAt = Tier.actTime w := by
  cases hoff : u.offeredAt with
  | floor =>
      change (rowLanguage G).TrueAt u.offeredAt u.content at hfit
      rw [hoff] at hfit
      exact hfit.elim
  | actTime w =>
      exact ⟨w, rfl⟩

/-- Ordinary conventional speech fits its offer: an `inForce` claim offered
    at any act-time tier is true there. The taxonomy's default verdict on
    ordinary speech is decline. -/
theorem inForce_fits_actTime_offer
    (u : RecordedUtterance G (rowLanguage G)) (r : RowTag)
    (hcontent : u.content = .inForce r)
    (w : G.Weld) (hoff : u.offeredAt = Tier.actTime w) :
    u.FitsOfferedTier := by
  change (rowLanguage G).TrueAt u.offeredAt u.content
  rw [hoff, hcontent]
  exact True.intro

/-- A floor offer is error-free by silence: it asserts nothing, so nothing
    convicts it. This is not a positive truth judgement at the floor. -/
theorem not_misfits_of_floor_offer
    (u : RecordedUtterance G (rowLanguage G))
    (hoff : u.offeredAt = Tier.floor) :
    ¬ u.MisfitsOfferedTier := by
  rintro ⟨w, hact, _hfalse⟩
  rw [hoff] at hact
  cases hact

/-- Failure to fit an act-time offer is exactly enough to introduce the
    conventional error predicate. -/
theorem misfits_of_not_fits_actTime
    (u : RecordedUtterance G (rowLanguage G)) (w : G.Weld)
    (hoff : u.offeredAt = Tier.actTime w) (hnot : ¬ u.FitsOfferedTier) :
    u.MisfitsOfferedTier :=
  ⟨w, hoff, hnot⟩

/-- A fitting offer cannot be a conventional misfit. -/
theorem not_misfits_of_fits
    (u : RecordedUtterance G (rowLanguage G)) (hfit : u.FitsOfferedTier) :
    ¬ u.MisfitsOfferedTier := by
  rintro ⟨_w, _hoff, hnot⟩
  exact hnot hfit

def rowOf (G : CoreReadings Designatum Contrib) (r : RowTag) : Distinction G :=
  { language := rowLanguage G
    sideA := .inForce r
    sideB := .denied r }

theorem rowOf_separated_at_live
    (r : RowTag) (t : Tier G) (ht : Tier.hasLiveShare G t) :
    (rowOf G r).Separated t := by
  constructor
  · exact ht
  · cases t with
    | floor =>
        cases ht
    | actTime w =>
        dsimp [rowOf, rowLanguage, ClaimLanguage.TrueAt]
        intro hiff
        exact ht (hiff.mp True.intro)

theorem rowOf_collapse_self_refuting
    (r : RowTag) (t : Tier G) :
    ¬ (rowOf G r).Collapse t := by
  intro hcollapse
  exact (rowOf_separated_at_live G r t hcollapse.left).right hcollapse.right

theorem rowOf_not_freeze (r : RowTag) :
    ¬ (rowOf G r).Freeze := by
  intro hfreeze
  apply hfreeze
  dsimp [rowOf, rowLanguage, ClaimLanguage.TrueAt]
  exact Iff.rfl

/-- The denial side can be true only where the offered tier is not live. -/
theorem denied_holds_only_where_no_live_share
    (r : RowTag) (t : Tier G)
    (h : (rowLanguage G).Holds t (.denied r)) :
    ¬ Tier.hasLiveShare G t := by
  cases t with
  | floor =>
      exact h.elim
  | actTime _ =>
      intro hLive
      exact hLive h

theorem rowOf_errorFree (r : RowTag) :
    ErrorFree G (rowOf G r) :=
  ⟨rowOf_collapse_self_refuting G r, rowOf_not_freeze G r⟩

theorem rowOf_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))]
    (r : RowTag) :
    (rowOf G r).ObeysSeparateFuse := by
  constructor
  · intro t hLive
    exact (rowOf_separated_at_live G r t hLive).right
  · intro t hNotLive
    cases t with
    | floor =>
        dsimp [rowOf, rowLanguage, ClaimLanguage.TrueAt]
        exact Iff.rfl
    | actTime w =>
        dsimp [rowOf, rowLanguage, ClaimLanguage.TrueAt]
        have hbot : AtBot (G.share w) := by
          by_cases h : AtBot (G.share w)
          · exact h
          · exact False.elim (hNotLive h)
        constructor
        · intro _h
          exact hbot
        · intro _h
          exact True.intro

/-- For the floor-apophatic row language, the refutation-only reading and full
    separate/fuse obedience coincide under the local decidability needed to
    turn `¬¬ AtBot` into `AtBot` at non-live act-times. This is not a generic
    theorem about arbitrary distinctions; the satori clause is the load-bearing
    premise. -/
theorem rowOf_obeys_iff_errorFree
    [∀ w : G.Weld, Decidable (AtBot (G.share w))]
    (r : RowTag) :
    (rowOf G r).ObeysSeparateFuse ↔ ErrorFree G (rowOf G r) :=
  ⟨Grid.errorFree_of_obeys G, fun _h => rowOf_obeys G r⟩

/-- At a pole-class act-time every schema-row claim is true there. This is
    truth at that weld and tier, not the pole as a truth-maker elsewhere. -/
theorem pole_validates_all_claims
    {w : G.Weld} (h : AtBot (G.share w)) :
    ∀ p, (rowLanguage G).Holds (Tier.actTime w) p := by
  intro p
  cases p with
  | inForce _ =>
      exact True.intro
  | denied _ =>
      exact h

/-- A live act-time refutes the denial side and the bare equivalence of the two
    sides. The conventional `inForce` side still stands. -/
theorem live_tier_refutes_denials_and_fusions
    (r : RowTag) (t : Tier G) (hLive : Tier.hasLiveShare G t) :
    (¬ (rowLanguage G).Holds t (.denied r)) ∧
      ¬ ((rowLanguage G).Holds t (.inForce r) ↔
        (rowLanguage G).Holds t (.denied r)) := by
  constructor
  · intro hdenied
    exact denied_holds_only_where_no_live_share G r t hdenied hLive
  · exact (rowOf_separated_at_live G r t hLive).right

/-- A denial offered at a live tier does not fit that offered tier. -/
theorem denied_misfits_live_offer
    (r : RowTag)
    (u : RecordedUtterance G (rowLanguage G))
    (hcontent : u.content = .denied r)
    (hlive : Tier.hasLiveShare G u.offeredAt) :
    ¬ RecordedUtterance.FitsOfferedTier u := by
  intro hfit
  change (rowLanguage G).TrueAt u.offeredAt u.content at hfit
  cases hoff : u.offeredAt with
  | floor =>
      rw [hoff] at hlive
      cases hlive
  | actTime w =>
      rw [hoff, hcontent] at hfit
      dsimp [rowLanguage, ClaimLanguage.TrueAt] at hfit
      rw [hoff] at hlive
      exact hlive hfit

/-- The error-predicate form of `denied_misfits_live_offer`: a live denial is
    not merely unfit but a conventional misfit. -/
theorem denied_misfits_live_offer_as_error
    (r : RowTag)
    (u : RecordedUtterance G (rowLanguage G))
    (hcontent : u.content = .denied r)
    (hlive : Tier.hasLiveShare G u.offeredAt) :
    u.MisfitsOfferedTier := by
  cases hoff : u.offeredAt with
  | floor =>
      rw [hoff] at hlive
      cases hlive
  | actTime w =>
      exact misfits_of_not_fits_actTime G u w hoff
        (denied_misfits_live_offer G r u hcontent hlive)

abbrev layerRow (G : CoreReadings Designatum Contrib) (l : ConventionLayer) : Distinction G :=
  rowOf G (.layer l)

abbrev beforeAfterRow (G : CoreReadings Designatum Contrib) : Distinction G :=
  rowOf G (.layer .directedTime)

abbrev beingsRow (G : CoreReadings Designatum Contrib) : Distinction G :=
  rowOf G (.layer .beings)

abbrev gridLensRow (G : CoreReadings Designatum Contrib) : Distinction G :=
  rowOf G (.layer .gridLens)

abbrev weldRow (G : CoreReadings Designatum Contrib) : Distinction G :=
  rowOf G (.layer .weldGrain)

abbrev intraWeldArrowRow (G : CoreReadings Designatum Contrib) : Distinction G :=
  rowOf G (.layer .intraWeldArrow)

theorem layerRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))]
    (l : ConventionLayer) :
    (layerRow G l).ObeysSeparateFuse :=
  rowOf_obeys G (.layer l)

theorem beforeAfterRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (beforeAfterRow G).ObeysSeparateFuse :=
  rowOf_obeys G (.layer .directedTime)

theorem beingsRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (beingsRow G).ObeysSeparateFuse :=
  rowOf_obeys G (.layer .beings)

theorem gridLensRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (gridLensRow G).ObeysSeparateFuse :=
  rowOf_obeys G (.layer .gridLens)

theorem weldRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (weldRow G).ObeysSeparateFuse :=
  rowOf_obeys G (.layer .weldGrain)

theorem intraWeldArrowRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (intraWeldArrowRow G).ObeysSeparateFuse :=
  rowOf_obeys G (.layer .intraWeldArrow)

/-- Compatibility name for the migrated layer denials. -/
theorem layerDenied_holds_only_where_no_live_share
    (l : ConventionLayer) (t : Tier G)
    (h : (rowLanguage G).Holds t (.denied (.layer l))) :
    ¬ Tier.hasLiveShare G t :=
  denied_holds_only_where_no_live_share G (.layer l) t h

theorem beforeAfterRow_not_freeze :
    ¬ (beforeAfterRow G).Freeze :=
  rowOf_not_freeze G (.layer .directedTime)

/-- The before/after collapse is self-refuting at every tier; in particular,
    it cannot be asserted as a live diagnosis. -/
theorem no_time_collapse_self_refuting (t : Tier G) :
    ¬ (beforeAfterRow G).Collapse t :=
  rowOf_collapse_self_refuting G (.layer .directedTime) t

/-- The beings row cannot freeze. The freeze cell in the prose table names the
    position this checked row rules out asserting: designation reified into
    ontology against `BeingNegative`. -/
theorem beingsRow_not_freeze :
    ¬ (beingsRow G).Freeze :=
  rowOf_not_freeze G (.layer .beings)

/-- "There are no beings", offered as a live diagnosis, is refuted by its own
    tier. -/
theorem no_beings_collapse_self_refuting (t : Tier G) :
    ¬ (beingsRow G).Collapse t :=
  rowOf_collapse_self_refuting G (.layer .beings) t

theorem gridLensRow_not_freeze :
    ¬ (gridLensRow G).Freeze :=
  rowOf_not_freeze G (.layer .gridLens)

theorem lens_denial_collapse_self_refuting (t : Tier G) :
    ¬ (gridLensRow G).Collapse t :=
  rowOf_collapse_self_refuting G (.layer .gridLens) t

theorem weldRow_not_freeze :
    ¬ (weldRow G).Freeze :=
  rowOf_not_freeze G (.layer .weldGrain)

theorem weldRow_errorFree :
    ErrorFree G (weldRow G) :=
  rowOf_errorFree G (.layer .weldGrain)

/-- "No acts happen", offered as a live diagnosis, is refuted by its own tier. -/
theorem weld_denial_collapse_self_refuting (t : Tier G) :
    ¬ (weldRow G).Collapse t :=
  rowOf_collapse_self_refuting G (.layer .weldGrain) t

theorem intraWeldArrowRow_not_freeze :
    ¬ (intraWeldArrowRow G).Freeze :=
  rowOf_not_freeze G (.layer .intraWeldArrow)

/-- "No call/response order, so no acts", offered live, is refuted by its own
    act-time tier. -/
theorem no_order_collapse_self_refuting (t : Tier G) :
    ¬ (intraWeldArrowRow G).Collapse t :=
  rowOf_collapse_self_refuting G (.layer .intraWeldArrow) t

abbrev rungPoleRow (G : CoreReadings Designatum Contrib) : Distinction G :=
  rowOf G .rungPole

theorem rungPoleRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (rungPoleRow G).ObeysSeparateFuse :=
  rowOf_obeys G .rungPole

theorem rungPoleRow_not_freeze :
    ¬ (rungPoleRow G).Freeze :=
  rowOf_not_freeze G .rungPole

/-- Kensho read as genjo collapses a rung into the pole. -/
theorem kensho_as_genjo_collapse_self_refuting (t : Tier G) :
    ¬ (rungPoleRow G).Collapse t :=
  rowOf_collapse_self_refuting G .rungPole t

abbrev foxWeldRow (G : CoreReadings Designatum Contrib) : Distinction G :=
  rowOf G .foxWeld

theorem foxWeldRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (foxWeldRow G).ObeysSeparateFuse :=
  rowOf_obeys G .foxWeld

theorem foxWeldRow_not_freeze :
    ¬ (foxWeldRow G).Freeze :=
  rowOf_not_freeze G .foxWeld

/-- The fox's "not-fall" side, offered as live diagnosis, is self-refuting. -/
theorem fox_notFall_collapse_self_refuting (t : Tier G) :
    ¬ (foxWeldRow G).Collapse t :=
  rowOf_collapse_self_refuting G .foxWeld t

/-- "Not-fall", offered where diagnosis is live, does not fit its offered
    tier: Case 2 checked against the schema row itself. -/
theorem fox_utterance_misfits_live_offer
    (u : RecordedUtterance G (rowLanguage G))
    (hcontent : u.content = .denied .foxWeld)
    (hlive : Tier.hasLiveShare G u.offeredAt) :
    ¬ RecordedUtterance.FitsOfferedTier u :=
  denied_misfits_live_offer G .foxWeld u hcontent hlive

abbrev doerDeedRow (G : CoreReadings Designatum Contrib) : Distinction G :=
  rowOf G .doerDeed

theorem doerDeedRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (doerDeedRow G).ObeysSeparateFuse :=
  rowOf_obeys G .doerDeed

theorem doerDeedRow_not_freeze :
    ¬ (doerDeedRow G).Freeze :=
  rowOf_not_freeze G .doerDeed

/-- "No doer, only deeds", offered as live diagnosis, is mounted by the very
    act-time being answering a call. -/
theorem no_prior_doer_collapse_self_refuting (t : Tier G) :
    ¬ (doerDeedRow G).Collapse t :=
  rowOf_collapse_self_refuting G .doerDeed t

abbrev functionShareRow (G : CoreReadings Designatum Contrib) : Distinction G :=
  rowOf G .functionShare

theorem functionShareRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (functionShareRow G).ObeysSeparateFuse :=
  rowOf_obeys G .functionShare

theorem functionShareRow_not_freeze :
    ¬ (functionShareRow G).Freeze :=
  rowOf_not_freeze G .functionShare

theorem function_share_cell_collapse_self_refuting (t : Tier G) :
    ¬ (functionShareRow G).Collapse t :=
  rowOf_collapse_self_refuting G .functionShare t

abbrev karmaIngaRow (G : CoreReadings Designatum Contrib) : Distinction G :=
  rowOf G .karmaInga

theorem karmaIngaRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (karmaIngaRow G).ObeysSeparateFuse :=
  rowOf_obeys G .karmaInga

theorem karmaIngaRow_not_freeze :
    ¬ (karmaIngaRow G).Freeze :=
  rowOf_not_freeze G .karmaInga

theorem misfeed_collapse_self_refuting (t : Tier G) :
    ¬ (karmaIngaRow G).Collapse t :=
  rowOf_collapse_self_refuting G .karmaInga t

abbrev sowingReapingRow (G : CoreReadings Designatum Contrib) : Distinction G :=
  rowOf G .sowingReaping

theorem sowingReapingRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (sowingReapingRow G).ObeysSeparateFuse :=
  rowOf_obeys G .sowingReaping

theorem sowingReapingRow_not_freeze :
    ¬ (sowingReapingRow G).Freeze :=
  rowOf_not_freeze G .sowingReaping

theorem series_ownership_collapse_self_refuting (t : Tier G) :
    ¬ (sowingReapingRow G).Collapse t :=
  rowOf_collapse_self_refuting G .sowingReaping t

abbrev deliveryIndexRow (G : CoreReadings Designatum Contrib) : Distinction G :=
  rowOf G .deliveryIndex

theorem deliveryIndexRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (deliveryIndexRow G).ObeysSeparateFuse :=
  rowOf_obeys G .deliveryIndex

theorem deliveryIndexRow_not_freeze :
    ¬ (deliveryIndexRow G).Freeze :=
  rowOf_not_freeze G .deliveryIndex

theorem misfed_register_collapse_self_refuting (t : Tier G) :
    ¬ (deliveryIndexRow G).Collapse t :=
  rowOf_collapse_self_refuting G .deliveryIndex t

abbrev weldEventTypeRow (G : CoreReadings Designatum Contrib) : Distinction G :=
  rowOf G .weldEventType

theorem weldEventTypeRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (weldEventTypeRow G).ObeysSeparateFuse :=
  rowOf_obeys G .weldEventType

theorem weldEventTypeRow_not_freeze :
    ¬ (weldEventTypeRow G).Freeze :=
  rowOf_not_freeze G .weldEventType

theorem eventType_grading_collapse_self_refuting (t : Tier G) :
    ¬ (weldEventTypeRow G).Collapse t :=
  rowOf_collapse_self_refuting G .weldEventType t

abbrev standingDatedRow (G : CoreReadings Designatum Contrib) : Distinction G :=
  rowOf G .standingDated

theorem standingDatedRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (standingDatedRow G).ObeysSeparateFuse :=
  rowOf_obeys G .standingDated

theorem standingDatedRow_not_freeze :
    ¬ (standingDatedRow G).Freeze :=
  rowOf_not_freeze G .standingDated

theorem prognosis_as_diagnosis_collapse_self_refuting (t : Tier G) :
    ¬ (standingDatedRow G).Collapse t :=
  rowOf_collapse_self_refuting G .standingDated t

abbrev subjectObjectAxisRow (G : CoreReadings Designatum Contrib) : Distinction G :=
  rowOf G .subjectObjectAxis

theorem subjectObjectAxisRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (subjectObjectAxisRow G).ObeysSeparateFuse :=
  rowOf_obeys G .subjectObjectAxis

theorem subjectObjectAxisRow_not_freeze :
    ¬ (subjectObjectAxisRow G).Freeze :=
  rowOf_not_freeze G .subjectObjectAxis

theorem object_axis_as_subject_collapse_self_refuting (t : Tier G) :
    ¬ (subjectObjectAxisRow G).Collapse t :=
  rowOf_collapse_self_refuting G .subjectObjectAxis t

/- Sentience is marked per weld by `SentienceReading`; treating the mark as a
   standing nature freezes this distinction, while identifying it with
   grid-visible function collapses the two sides. The generic row machinery
   checks the taxonomy shape without pretending to recover the supplied mark. -/
abbrev standingSentienceRow (G : CoreReadings Designatum Contrib) : Distinction G :=
  rowOf G .standingSentience

theorem standingSentienceRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (standingSentienceRow G).ObeysSeparateFuse :=
  rowOf_obeys G .standingSentience

theorem standingSentienceRow_not_freeze :
    ¬ (standingSentienceRow G).Freeze :=
  rowOf_not_freeze G .standingSentience

theorem sentience_from_function_collapse_self_refuting (t : Tier G) :
    ¬ (standingSentienceRow G).Collapse t :=
  rowOf_collapse_self_refuting G .standingSentience t

abbrev perCallGlobalRow (G : CoreReadings Designatum Contrib) : Distinction G :=
  rowOf G .perCallGlobal

theorem perCallGlobalRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (perCallGlobalRow G).ObeysSeparateFuse :=
  rowOf_obeys G .perCallGlobal

theorem perCallGlobalRow_not_freeze :
    ¬ (perCallGlobalRow G).Freeze :=
  rowOf_not_freeze G .perCallGlobal

theorem perCallGlobal_collapse_self_refuting (t : Tier G) :
    ¬ (perCallGlobalRow G).Collapse t :=
  rowOf_collapse_self_refuting G .perCallGlobal t

abbrev terminusExitRow (G : CoreReadings Designatum Contrib) : Distinction G :=
  rowOf G .terminusExit

theorem terminusExitRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (terminusExitRow G).ObeysSeparateFuse :=
  rowOf_obeys G .terminusExit

theorem terminusExitRow_not_freeze :
    ¬ (terminusExitRow G).Freeze :=
  rowOf_not_freeze G .terminusExit

theorem exit_collapse_self_refuting (t : Tier G) :
    ¬ (terminusExitRow G).Collapse t :=
  rowOf_collapse_self_refuting G .terminusExit t

abbrev selfPoleTransposedRow (G : CoreReadings Designatum Contrib) : Distinction G :=
  rowOf G .selfPoleTransposed

theorem selfPoleTransposedRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (selfPoleTransposedRow G).ObeysSeparateFuse :=
  rowOf_obeys G .selfPoleTransposed

theorem selfPoleTransposedRow_not_freeze :
    ¬ (selfPoleTransposedRow G).Freeze :=
  rowOf_not_freeze G .selfPoleTransposed

theorem transposition_erased_downward_collapse_self_refuting (t : Tier G) :
    ¬ (selfPoleTransposedRow G).Collapse t :=
  rowOf_collapse_self_refuting G .selfPoleTransposed t

/-- Rows of the Grade-1 table that remain prose; their reasons are recorded in
    Identification/Commentary.lean and the paper commentary. -/
inductive ProseRow
  | beingNonBeing
  | ladderTerminus
  | genjoSho
  | shoSatori
  | row2Row3
  | descriptionInjunction

/-- A table row is schema-generated, ladder-generated, or prose. -/
inductive TableRow
  | generated (r : RowTag)
  | ladderSchema
  | prose (p : ProseRow)

/- Scope note, against over-diagnosis. The table grades offers, not
   sentences: the generator's unit is `RecordedUtterance` — content carried
   with its call and its offered tier — and a sentence-shape alone is not in
   the domain (the gradeability discipline's limit case; compare
   `severed_transcript_ungradeable`). Ordinary conventional speech is the
   validated default, not the suspect case: the row language makes each
   row's conventional side hold wherever an act is under way — validity by
   stipulation, not an achievement of the sentence (`rowLanguage`,
   `inForce_fits_actTime_offer`) — so narration that merely exercises the
   being, doer/deed, before/after, and weld-grain conventions, "a man
   walked into a bar", violates none of them, and the generator's standing
   verdict on it is decline. Errors enter with the offer, never with the
   words: the same words carried by a different offer are a different
   recorded utterance — held out as floor-furniture they stack freezes per
   distinction touched; their denial, offered as live diagnosis, stacks
   collapses. A diagnosis that convicts the sentence itself is the
   over-generation the decline verdict fences. -/

def tableOrder : List TableRow := [
  .prose .beingNonBeing,
  .ladderSchema,
  .prose .ladderTerminus,
  .generated .rungPole,
  .prose .genjoSho,
  .prose .shoSatori,
  .generated .foxWeld,
  .prose .row2Row3,
  .generated .doerDeed,
  .generated .functionShare,
  .generated .karmaInga,
  .generated .sowingReaping,
  .generated .deliveryIndex,
  .generated .weldEventType,
  .generated .standingDated,
  .generated .subjectObjectAxis,
  .generated .standingSentience,
  .generated .perCallGlobal,
  .prose .descriptionInjunction,
  .generated (.layer .gridLens),
  .generated .terminusExit,
  .generated .selfPoleTransposed,
  .generated (.layer .directedTime),
  .generated (.layer .intraWeldArrow),
  .generated (.layer .beings),
  .generated (.layer .weldGrain) ]

example : tableOrder.length = 26 := rfl

/-- Metadata for whether a schema-generated row has a collapse occupant in the
    paper's Grade-1 table. This records table prose; it is not extra grid
    semantics. -/
def hasCollapseOccupant : RowTag → Bool
  | .perCallGlobal => false
  | _ => true

/-- Metadata for whether a schema-generated row has a freeze occupant in the
    paper's Grade-1 table. This records table prose; it is not extra grid
    semantics. -/
def hasFreezeOccupant : RowTag → Bool
  | _ => true

/-- A generated table dash is data, while the row's refutations remain theorem
    facts. The per-call/global row has no collapse occupant in the table, yet
    collapse and freeze are still ruled out by the row checks. -/
theorem perCallGlobal_empty_collapse_cell_anchor :
    hasCollapseOccupant .perCallGlobal = false ∧
      hasFreezeOccupant .perCallGlobal = true ∧
        (∀ t, ¬ (perCallGlobalRow G).Collapse t) ∧
          ¬ (perCallGlobalRow G).Freeze :=
  ⟨rfl, rfl, fun t => perCallGlobal_collapse_self_refuting G t,
    perCallGlobalRow_not_freeze G⟩

end GridConvention
end BeingConvention
end DirectedConvention

end Grid

/-- A live terminus supplies an actual pole-share weld in its own agent fiber.
    This is mark-free: no sentience reading is needed to inhabit the tier. -/
theorem poleTier_inhabited_of_liveTerminus
    {Designatum Contrib : Type} [PreorderBot Contrib]
    {G : CoreReadings Designatum Contrib} {b : Designatum}
    (h : G.LiveTerminus b) :
    ∃ w : G.Weld, G.Actual w ∧ w.agent = b ∧
      AtBot (G.share w) ∧ G.AtPoleClass w.agent := by
  rcases h.left with ⟨w, hactual, hagent⟩
  refine ⟨w, hactual, hagent, ?_, ?_⟩
  · exact h.right w hactual hagent
  · simpa [Grid.AtPoleClass, hagent] using h.right

/-- `LiveTerminus` fixes the pole-share witness, while the supplied mark
    conditionally determines which row of the act square contains it.  The
    theorem remains constructive by making neither row choice itself. -/
theorem poleTier_cell_of_liveTerminus
    {Designatum Contrib : Type} [PreorderBot Contrib]
    {G : CoreReadings Designatum Contrib} {b : Designatum}
    (S : G.SentienceReading) (h : G.LiveTerminus b) :
    ∃ w : G.Weld, w.agent = b ∧ AtBot (G.share w) ∧
      (S.sentient w → G.TerminusAct S w) ∧
      (¬ S.sentient w → G.StoneAct S w) := by
  rcases poleTier_inhabited_of_liveTerminus h with
    ⟨w, hactual, hagent, hbot, _hatPole⟩
  exact ⟨w, hagent, hbot,
    fun hmarked => ⟨⟨hactual, hmarked⟩, hbot⟩,
    fun hunmarked => ⟨⟨hactual, hunmarked⟩, hbot⟩⟩

/-- Assertable and displayable are different verdict voices. -/
theorem assertable_ne_displayable :
    Grid.VerdictVoice.assertable ≠ Grid.VerdictVoice.displayable := by
  intro h
  cases h

end WAA
