/-
================================================================================
  WeldAndArrow.Consequences.Taxonomy
  Error taxonomy, table order, content rows, ladders, and witnesses
================================================================================

Reading and motivation: Identification/Commentary.lean, C.2.
-/

import WeldAndArrow.Consequences.Basic

namespace WAA

namespace Grid

variable {Contrib : Type} [PreorderBot Contrib]
variable (G : Grid Contrib)

namespace DirectedConvention
namespace BeingConvention
namespace GridConvention

/- The lens's own vocabulary: the innermost convention. The abstract
   `ClaimLanguage` machinery remains at `Grid` level; this namespace supplies
   the concrete rows generated from it. -/

/-- The nested conventions as objects the lens can diagnose claims about. -/
inductive ConventionLayer
  | directedTime
  | beings
  | gridLens

/-- Claims for convention-layer rows. `conventionLive l` says the layer's
    distinction is in force; `layerDenied l` is the deflation. -/
inductive LayerClaim
  | conventionLive (l : ConventionLayer)
  | layerDenied (l : ConventionLayer)

/-- Every schema-generated row of the Grade-1 table, as inspectable data. The
    three convention layers embed via `layer`; the level-n row is generated by
    `ladder` instead. -/
inductive RowTag
  | layer (l : ConventionLayer)
  | foxWeld
  | rungPole
  | functionShare
  | karmaInga
  | sowingReaping
  | deliveryIndex
  | weldEventType
  | standingDated
  | subjectObjectAxis
  | undefinedZero
  | perCallGlobal
  | terminusExit
  | selfPoleTransposed

/-- The two sides of a schema-generated row. `inForce r` is the conventional
    side; `denied r` is the floor-side deflation offered as diagnosis. -/
inductive RowClaim
  | inForce (r : RowTag)
  | denied (r : RowTag)

/-- Pole-affirming semantics. The conventional side is true at every act-time;
    the denial side is true at act-time exactly at the pole-class. Thus a
    pole-class act-time validates both sides by truth, not vacuity. -/
def rowLanguage (G : Grid Contrib) : ClaimLanguage G where
  Claim := RowClaim
  Holds
    | .floor, _ => True
    | .actTime _, .inForce _ => True
    | .actTime w, .denied _ => AtBot (G.share w)

def rowOf (G : Grid Contrib) (r : RowTag) : Distinction G :=
  { language := rowLanguage G
    sideA := .inForce r
    sideB := .denied r }

theorem rowOf_separated_at_live
    (r : RowTag) (t : Tier G) (ht : Tier.hasLiveShare G t) :
    (rowOf G r).Separated t := by
  constructor
  · exact ht
  · cases t with
    | floor =>
        cases ht
    | actTime w =>
        dsimp [rowOf, rowLanguage, ClaimLanguage.TrueAt]
        intro hiff
        exact ht (hiff.mp True.intro)

theorem rowOf_collapse_self_refuting
    (r : RowTag) (t : Tier G) :
    ¬ (rowOf G r).Collapse t := by
  intro hcollapse
  exact (rowOf_separated_at_live G r t hcollapse.left).right hcollapse.right

theorem rowOf_not_freeze (r : RowTag) :
    ¬ (rowOf G r).Freeze := by
  intro hfreeze
  apply hfreeze
  dsimp [rowOf, rowLanguage, ClaimLanguage.TrueAt]
  constructor <;> intro _ <;> exact True.intro

/-- The denial side can be true only where the offered tier is not live. -/
theorem denied_holds_only_where_no_live_share
    (r : RowTag) (t : Tier G)
    (h : (rowLanguage G).Holds t (.denied r)) :
    ¬ Tier.hasLiveShare G t := by
  cases t with
  | floor =>
      intro hfloor
      exact hfloor
  | actTime _ =>
      intro hLive
      exact hLive h

theorem rowOf_errorFree (r : RowTag) :
    ErrorFree G (rowOf G r) :=
  ⟨rowOf_collapse_self_refuting G r, rowOf_not_freeze G r⟩

theorem rowOf_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))]
    (r : RowTag) :
    (rowOf G r).ObeysSeparateFuse := by
  constructor
  · intro t hLive
    exact (rowOf_separated_at_live G r t hLive).right
  · intro t hNotLive
    cases t with
    | floor =>
        dsimp [rowOf, rowLanguage, ClaimLanguage.TrueAt]
        constructor <;> intro _ <;> exact True.intro
    | actTime w =>
        dsimp [rowOf, rowLanguage, ClaimLanguage.TrueAt]
        have hbot : AtBot (G.share w) := by
          by_cases h : AtBot (G.share w)
          · exact h
          · exact False.elim (hNotLive h)
        constructor
        · intro _h
          exact hbot
        · intro _h
          exact True.intro

/-- For the pole-affirming row language, the refutation-only reading and full
    separate/fuse obedience coincide under the local decidability needed to
    turn `¬¬ AtBot` into `AtBot` at non-live act-times. This is not a generic
    theorem about arbitrary distinctions; the satori clause is the load-bearing
    premise. -/
theorem rowOf_obeys_iff_errorFree
    [∀ w : G.Weld, Decidable (AtBot (G.share w))]
    (r : RowTag) :
    (rowOf G r).ObeysSeparateFuse ↔ ErrorFree G (rowOf G r) :=
  ⟨Grid.errorFree_of_obeys G, fun _h => rowOf_obeys G r⟩

/-- At a pole-class act-time every schema-row claim is true there. This is
    truth at that weld and tier, not the pole as a truth-maker elsewhere. -/
theorem pole_validates_all_claims
    {w : G.Weld} (h : AtBot (G.share w)) :
    ∀ p, (rowLanguage G).Holds (Tier.actTime w) p := by
  intro p
  cases p with
  | inForce _ =>
      exact True.intro
  | denied _ =>
      exact h

/-- A live act-time refutes the denial side and the bare equivalence of the two
    sides. The conventional `inForce` side still stands. -/
theorem live_tier_refutes_denials_and_fusions
    (r : RowTag) (t : Tier G) (hLive : Tier.hasLiveShare G t) :
    (¬ (rowLanguage G).Holds t (.denied r)) ∧
      ¬ ((rowLanguage G).Holds t (.inForce r) ↔
        (rowLanguage G).Holds t (.denied r)) := by
  constructor
  · intro hdenied
    exact denied_holds_only_where_no_live_share G r t hdenied hLive
  · exact (rowOf_separated_at_live G r t hLive).right

/-- A denial offered at a live tier does not fit that offered tier. -/
theorem denied_misfits_live_offer
    (r : RowTag)
    (u : RecordedUtterance G (rowLanguage G))
    (hcontent : u.content = .denied r)
    (hlive : Tier.hasLiveShare G u.offeredAt) :
    ¬ RecordedUtterance.FitsOfferedTier u := by
  intro hfit
  change (rowLanguage G).TrueAt u.offeredAt u.content at hfit
  cases hoff : u.offeredAt with
  | floor =>
      rw [hoff] at hlive
      cases hlive
  | actTime w =>
      rw [hoff, hcontent] at hfit
      dsimp [rowLanguage, ClaimLanguage.TrueAt] at hfit
      rw [hoff] at hlive
      exact hlive hfit

abbrev layerRow (G : Grid Contrib) (l : ConventionLayer) : Distinction G :=
  rowOf G (.layer l)

abbrev beforeAfterRow (G : Grid Contrib) : Distinction G :=
  rowOf G (.layer .directedTime)

abbrev beingsRow (G : Grid Contrib) : Distinction G :=
  rowOf G (.layer .beings)

abbrev gridLensRow (G : Grid Contrib) : Distinction G :=
  rowOf G (.layer .gridLens)

theorem layerRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))]
    (l : ConventionLayer) :
    (layerRow G l).ObeysSeparateFuse :=
  rowOf_obeys G (.layer l)

theorem beforeAfterRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (beforeAfterRow G).ObeysSeparateFuse :=
  rowOf_obeys G (.layer .directedTime)

theorem beingsRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (beingsRow G).ObeysSeparateFuse :=
  rowOf_obeys G (.layer .beings)

theorem gridLensRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (gridLensRow G).ObeysSeparateFuse :=
  rowOf_obeys G (.layer .gridLens)

/-- Compatibility name for the migrated layer denials. -/
theorem layerDenied_holds_only_where_no_live_share
    (l : ConventionLayer) (t : Tier G)
    (h : (rowLanguage G).Holds t (.denied (.layer l))) :
    ¬ Tier.hasLiveShare G t :=
  denied_holds_only_where_no_live_share G (.layer l) t h

theorem beforeAfterRow_not_freeze :
    ¬ (beforeAfterRow G).Freeze :=
  rowOf_not_freeze G (.layer .directedTime)

/-- The before/after collapse is self-refuting at every tier; in particular,
    it cannot be asserted as a live diagnosis. -/
theorem no_time_collapse_self_refuting (t : Tier G) :
    ¬ (beforeAfterRow G).Collapse t :=
  rowOf_collapse_self_refuting G (.layer .directedTime) t

/-- The beings row cannot freeze. The freeze cell in the prose table names the
    position this checked row rules out asserting: designation reified into
    ontology against `BeingNegative`. -/
theorem beingsRow_not_freeze :
    ¬ (beingsRow G).Freeze :=
  rowOf_not_freeze G (.layer .beings)

/-- "There are no beings", offered as a live diagnosis, is refuted by its own
    tier. -/
theorem no_beings_collapse_self_refuting (t : Tier G) :
    ¬ (beingsRow G).Collapse t :=
  rowOf_collapse_self_refuting G (.layer .beings) t

theorem gridLensRow_not_freeze :
    ¬ (gridLensRow G).Freeze :=
  rowOf_not_freeze G (.layer .gridLens)

theorem lens_denial_collapse_self_refuting (t : Tier G) :
    ¬ (gridLensRow G).Collapse t :=
  rowOf_collapse_self_refuting G (.layer .gridLens) t

abbrev rungPoleRow (G : Grid Contrib) : Distinction G :=
  rowOf G .rungPole

theorem rungPoleRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (rungPoleRow G).ObeysSeparateFuse :=
  rowOf_obeys G .rungPole

theorem rungPoleRow_not_freeze :
    ¬ (rungPoleRow G).Freeze :=
  rowOf_not_freeze G .rungPole

/-- Kensho read as genjo collapses a rung into the pole. -/
theorem kensho_as_genjo_collapse_self_refuting (t : Tier G) :
    ¬ (rungPoleRow G).Collapse t :=
  rowOf_collapse_self_refuting G .rungPole t

abbrev foxWeldRow (G : Grid Contrib) : Distinction G :=
  rowOf G .foxWeld

theorem foxWeldRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (foxWeldRow G).ObeysSeparateFuse :=
  rowOf_obeys G .foxWeld

theorem foxWeldRow_not_freeze :
    ¬ (foxWeldRow G).Freeze :=
  rowOf_not_freeze G .foxWeld

/-- The fox's "not-fall" side, offered as live diagnosis, is self-refuting. -/
theorem fox_notFall_collapse_self_refuting (t : Tier G) :
    ¬ (foxWeldRow G).Collapse t :=
  rowOf_collapse_self_refuting G .foxWeld t

/-- "Not-fall", offered where diagnosis is live, does not fit its offered
    tier: Case 2 checked against the schema row itself. -/
theorem fox_utterance_misfits_live_offer
    (u : RecordedUtterance G (rowLanguage G))
    (hcontent : u.content = .denied .foxWeld)
    (hlive : Tier.hasLiveShare G u.offeredAt) :
    ¬ RecordedUtterance.FitsOfferedTier u :=
  denied_misfits_live_offer G .foxWeld u hcontent hlive

abbrev functionShareRow (G : Grid Contrib) : Distinction G :=
  rowOf G .functionShare

theorem functionShareRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (functionShareRow G).ObeysSeparateFuse :=
  rowOf_obeys G .functionShare

theorem functionShareRow_not_freeze :
    ¬ (functionShareRow G).Freeze :=
  rowOf_not_freeze G .functionShare

theorem functionZero_from_shareZero_collapse_self_refuting (t : Tier G) :
    ¬ (functionShareRow G).Collapse t :=
  rowOf_collapse_self_refuting G .functionShare t

abbrev karmaIngaRow (G : Grid Contrib) : Distinction G :=
  rowOf G .karmaInga

theorem karmaIngaRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (karmaIngaRow G).ObeysSeparateFuse :=
  rowOf_obeys G .karmaInga

theorem karmaIngaRow_not_freeze :
    ¬ (karmaIngaRow G).Freeze :=
  rowOf_not_freeze G .karmaInga

theorem misfeed_collapse_self_refuting (t : Tier G) :
    ¬ (karmaIngaRow G).Collapse t :=
  rowOf_collapse_self_refuting G .karmaInga t

abbrev sowingReapingRow (G : Grid Contrib) : Distinction G :=
  rowOf G .sowingReaping

theorem sowingReapingRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (sowingReapingRow G).ObeysSeparateFuse :=
  rowOf_obeys G .sowingReaping

theorem sowingReapingRow_not_freeze :
    ¬ (sowingReapingRow G).Freeze :=
  rowOf_not_freeze G .sowingReaping

theorem series_ownership_collapse_self_refuting (t : Tier G) :
    ¬ (sowingReapingRow G).Collapse t :=
  rowOf_collapse_self_refuting G .sowingReaping t

abbrev deliveryIndexRow (G : Grid Contrib) : Distinction G :=
  rowOf G .deliveryIndex

theorem deliveryIndexRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (deliveryIndexRow G).ObeysSeparateFuse :=
  rowOf_obeys G .deliveryIndex

theorem deliveryIndexRow_not_freeze :
    ¬ (deliveryIndexRow G).Freeze :=
  rowOf_not_freeze G .deliveryIndex

theorem misfed_register_collapse_self_refuting (t : Tier G) :
    ¬ (deliveryIndexRow G).Collapse t :=
  rowOf_collapse_self_refuting G .deliveryIndex t

abbrev weldEventTypeRow (G : Grid Contrib) : Distinction G :=
  rowOf G .weldEventType

theorem weldEventTypeRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (weldEventTypeRow G).ObeysSeparateFuse :=
  rowOf_obeys G .weldEventType

theorem weldEventTypeRow_not_freeze :
    ¬ (weldEventTypeRow G).Freeze :=
  rowOf_not_freeze G .weldEventType

theorem eventType_grading_collapse_self_refuting (t : Tier G) :
    ¬ (weldEventTypeRow G).Collapse t :=
  rowOf_collapse_self_refuting G .weldEventType t

abbrev standingDatedRow (G : Grid Contrib) : Distinction G :=
  rowOf G .standingDated

theorem standingDatedRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (standingDatedRow G).ObeysSeparateFuse :=
  rowOf_obeys G .standingDated

theorem standingDatedRow_not_freeze :
    ¬ (standingDatedRow G).Freeze :=
  rowOf_not_freeze G .standingDated

theorem prognosis_as_diagnosis_collapse_self_refuting (t : Tier G) :
    ¬ (standingDatedRow G).Collapse t :=
  rowOf_collapse_self_refuting G .standingDated t

abbrev subjectObjectAxisRow (G : Grid Contrib) : Distinction G :=
  rowOf G .subjectObjectAxis

theorem subjectObjectAxisRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (subjectObjectAxisRow G).ObeysSeparateFuse :=
  rowOf_obeys G .subjectObjectAxis

theorem subjectObjectAxisRow_not_freeze :
    ¬ (subjectObjectAxisRow G).Freeze :=
  rowOf_not_freeze G .subjectObjectAxis

theorem insentient_subject_collapse_self_refuting (t : Tier G) :
    ¬ (subjectObjectAxisRow G).Collapse t :=
  rowOf_collapse_self_refuting G .subjectObjectAxis t

abbrev undefinedZeroRow (G : Grid Contrib) : Distinction G :=
  rowOf G .undefinedZero

theorem undefinedZeroRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (undefinedZeroRow G).ObeysSeparateFuse :=
  rowOf_obeys G .undefinedZero

theorem undefinedZeroRow_not_freeze :
    ¬ (undefinedZeroRow G).Freeze :=
  rowOf_not_freeze G .undefinedZero

theorem undefined_as_openness_collapse_self_refuting (t : Tier G) :
    ¬ (undefinedZeroRow G).Collapse t :=
  rowOf_collapse_self_refuting G .undefinedZero t

abbrev perCallGlobalRow (G : Grid Contrib) : Distinction G :=
  rowOf G .perCallGlobal

theorem perCallGlobalRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (perCallGlobalRow G).ObeysSeparateFuse :=
  rowOf_obeys G .perCallGlobal

theorem perCallGlobalRow_not_freeze :
    ¬ (perCallGlobalRow G).Freeze :=
  rowOf_not_freeze G .perCallGlobal

theorem perCallGlobal_collapse_self_refuting (t : Tier G) :
    ¬ (perCallGlobalRow G).Collapse t :=
  rowOf_collapse_self_refuting G .perCallGlobal t

abbrev terminusExitRow (G : Grid Contrib) : Distinction G :=
  rowOf G .terminusExit

theorem terminusExitRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (terminusExitRow G).ObeysSeparateFuse :=
  rowOf_obeys G .terminusExit

theorem terminusExitRow_not_freeze :
    ¬ (terminusExitRow G).Freeze :=
  rowOf_not_freeze G .terminusExit

theorem exit_collapse_self_refuting (t : Tier G) :
    ¬ (terminusExitRow G).Collapse t :=
  rowOf_collapse_self_refuting G .terminusExit t

abbrev selfPoleTransposedRow (G : Grid Contrib) : Distinction G :=
  rowOf G .selfPoleTransposed

theorem selfPoleTransposedRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (selfPoleTransposedRow G).ObeysSeparateFuse :=
  rowOf_obeys G .selfPoleTransposed

theorem selfPoleTransposedRow_not_freeze :
    ¬ (selfPoleTransposedRow G).Freeze :=
  rowOf_not_freeze G .selfPoleTransposed

theorem transposition_erased_downward_collapse_self_refuting (t : Tier G) :
    ¬ (selfPoleTransposedRow G).Collapse t :=
  rowOf_collapse_self_refuting G .selfPoleTransposed t

/-- Rows of the Grade-1 table that remain prose; their reasons are recorded in
    Identification/Commentary.lean and the paper commentary. -/
inductive ProseRow
  | beingNonBeing
  | ladderTerminus
  | genjoSho
  | shoSatori
  | row2Row3
  | descriptionInjunction

/-- A table row is schema-generated, ladder-generated, or prose. -/
inductive TableRow
  | generated (r : RowTag)
  | ladderSchema
  | prose (p : ProseRow)

def tableOrder : List TableRow := [
  .prose .beingNonBeing,
  .ladderSchema,
  .prose .ladderTerminus,
  .generated .rungPole,
  .prose .genjoSho,
  .prose .shoSatori,
  .generated .foxWeld,
  .prose .row2Row3,
  .generated .functionShare,
  .generated .karmaInga,
  .generated .sowingReaping,
  .generated .deliveryIndex,
  .generated .weldEventType,
  .generated .standingDated,
  .generated .subjectObjectAxis,
  .generated .undefinedZero,
  .generated .perCallGlobal,
  .prose .descriptionInjunction,
  .generated (.layer .gridLens),
  .generated .terminusExit,
  .generated .selfPoleTransposed,
  .generated (.layer .directedTime),
  .generated (.layer .beings) ]

example : tableOrder.length = 23 := rfl

/- --------------------------------------------------------------------------
   Content-bearing layer rows
-------------------------------------------------------------------------- -/

/-- Content-bearing language for the same layer claims. The convention-live
    side is still the live-share condition; the denial side now has content
    specific to the row. -/
def contentLayerLanguage (G : Grid Contrib) : ClaimLanguage G where
  Claim := LayerClaim
  Holds
    | .floor, _ => True
    | .actTime w, .conventionLive _ => G.HasSelfPoleIndex w
    | .actTime _, .layerDenied .directedTime => DirectionVoid Contrib
    | .actTime _, .layerDenied .beings => G.AllStone
    | .actTime _, .layerDenied .gridLens => ∀ t : Tier G, ¬ Tier.hasLiveShare G t

def contentLayerRow (G : Grid Contrib) (l : ConventionLayer) : Distinction G :=
  { language := contentLayerLanguage G
    sideA := .conventionLive l
    sideB := .layerDenied l }

def contentBeforeAfterRow (G : Grid Contrib) : Distinction G :=
  contentLayerRow G .directedTime

def contentBeingsRow (G : Grid Contrib) : Distinction G :=
  contentLayerRow G .beings

def contentGridLensRow (G : Grid Contrib) : Distinction G :=
  contentLayerRow G .gridLens

theorem contentLayerRow_obeys_of_direction
    (h : ∃ a b : Contrib, Strict a b) :
    (contentLayerRow G .directedTime).ObeysSeparateFuse := by
  rcases h with ⟨a, b, hstrict⟩
  constructor
  · intro t hLive
    cases t with
    | floor =>
        cases hLive
    | actTime _ =>
        dsimp [contentLayerRow, contentLayerLanguage, ClaimLanguage.TrueAt]
        intro hiff
        exact (hiff.mp hLive) a b hstrict
  · intro t hNotLive
    cases t with
    | floor =>
        constructor <;> intro _ <;> exact True.intro
    | actTime _ =>
        dsimp [contentLayerRow, contentLayerLanguage, ClaimLanguage.TrueAt]
        constructor
        · intro hLive
          exact False.elim (hNotLive hLive)
        · intro hvoid
          exact False.elim (hvoid a b hstrict)

theorem contentLayerRow_obeys_of_being
    (h : ∃ b : G.Being, ¬ G.Stone b) :
    (contentLayerRow G .beings).ObeysSeparateFuse := by
  rcases h with ⟨b, hnotStone⟩
  constructor
  · intro t hLive
    cases t with
    | floor =>
        cases hLive
    | actTime _ =>
        dsimp [contentLayerRow, contentLayerLanguage, ClaimLanguage.TrueAt]
        intro hiff
        exact hnotStone ((hiff.mp hLive) b)
  · intro t hNotLive
    cases t with
    | floor =>
        constructor <;> intro _ <;> exact True.intro
    | actTime _ =>
        dsimp [contentLayerRow, contentLayerLanguage, ClaimLanguage.TrueAt]
        constructor
        · intro hLive
          exact False.elim (hNotLive hLive)
        · intro hall
          exact False.elim (hnotStone (hall b))

theorem contentLayerRow_obeys_of_liveTier
    (h : ∃ t : Tier G, Tier.hasLiveShare G t) :
    (contentLayerRow G .gridLens).ObeysSeparateFuse := by
  rcases h with ⟨liveTier, hLiveTier⟩
  constructor
  · intro t hLive
    cases t with
    | floor =>
        cases hLive
    | actTime _ =>
        dsimp [contentLayerRow, contentLayerLanguage, ClaimLanguage.TrueAt]
        intro hiff
        exact (hiff.mp hLive) liveTier hLiveTier
  · intro t hNotLive
    cases t with
    | floor =>
        constructor <;> intro _ <;> exact True.intro
    | actTime _ =>
        dsimp [contentLayerRow, contentLayerLanguage, ClaimLanguage.TrueAt]
        constructor
        · intro hLive
          exact False.elim (hNotLive hLive)
        · intro hnoLive
          exact False.elim (hnoLive liveTier hLiveTier)

theorem contentBeforeAfterRow_obeys_of_direction
    (h : ∃ a b : Contrib, Strict a b) :
    (contentBeforeAfterRow G).ObeysSeparateFuse :=
  contentLayerRow_obeys_of_direction G h

theorem contentBeingsRow_obeys_of_being
    (h : ∃ b : G.Being, ¬ G.Stone b) :
    (contentBeingsRow G).ObeysSeparateFuse :=
  contentLayerRow_obeys_of_being G h

theorem contentGridLensRow_obeys_of_liveTier
    (h : ∃ t : Tier G, Tier.hasLiveShare G t) :
    (contentGridLensRow G).ObeysSeparateFuse :=
  contentLayerRow_obeys_of_liveTier G h

/-- An actual utterance of the beings-denial cannot fit an act-time tier:
    the utterer's actual response supplies a non-stone witness. -/
theorem beings_denial_fits_only_floor
    (u : RecordedUtterance G (contentLayerLanguage G))
    (hc : u.content = .layerDenied .beings)
    (w' : G.Weld) (ht : u.offeredAt = .actTime w') :
    ¬ u.FitsOfferedTier := by
  intro hfit
  change (contentLayerLanguage G).TrueAt u.offeredAt u.content at hfit
  rw [ht, hc] at hfit
  dsimp [contentLayerLanguage, ClaimLanguage.TrueAt] at hfit
  exact (G.not_stone_of_actual u.weld u.actual) (hfit u.weld.agent)

/-- A directed-time denial offered by an appropriating utterer cannot fit an
    act-time tier: the utterer's live share is itself a strict direction. -/
theorem time_denial_unfit_for_appropriating_utterer
    (u : RecordedUtterance G (contentLayerLanguage G))
    (hc : u.content = .layerDenied .directedTime)
    (hidx : G.HasSelfPoleIndex u.weld)
    (w' : G.Weld) (ht : u.offeredAt = .actTime w') :
    ¬ u.FitsOfferedTier := by
  intro hfit
  change (contentLayerLanguage G).TrueAt u.offeredAt u.content at hfit
  rw [ht, hc] at hfit
  dsimp [contentLayerLanguage, ClaimLanguage.TrueAt] at hfit
  exact hfit (shareBot : Contrib) (G.share u.weld)
    (G.strict_shareBot_of_hasSelfPoleIndex u.weld hidx)

/- --------------------------------------------------------------------------
   Re-emptying ladder
-------------------------------------------------------------------------- -/

/-- The two sides used to re-empty a distinction. Deliberately, neither side
    quantifies over ladder levels; level-quantification stays in meta-theorems. -/
inductive LadderSide
  | liveBelow
  | finalBelow

/-- Re-empty a distinction: the new row separates the lower row's live
    separation from the claim that the lower row survives the floor. -/
def reEmptied {G : Grid Contrib} (d : Distinction G) : Distinction G where
  language :=
    { Claim := LadderSide
      Holds := fun t c =>
        match t, c with
        | .floor, _ => True
        | .actTime w, .liveBelow => d.Separated (.actTime w)
        | .actTime _, .finalBelow => d.Freeze }
  sideA := .liveBelow
  sideB := .finalBelow

def ladder {G : Grid Contrib} (d : Distinction G) : Nat → Distinction G
  | 0 => d
  | n + 1 => reEmptied (ladder d n)

theorem reEmptied_obeysSeparateFuse
    {d : Distinction G} (h : d.ObeysSeparateFuse) :
    (reEmptied d).ObeysSeparateFuse := by
  constructor
  · intro t hLive
    cases t with
    | floor =>
        cases hLive
    | actTime _ =>
        dsimp [reEmptied, ClaimLanguage.TrueAt]
        intro hiff
        exact (Grid.not_freeze_of_obeysSeparateFuse h)
          (hiff.mp (G.separated_of_obeysSeparateFuse h hLive))
  · intro t hNotLive
    cases t with
    | floor =>
        constructor <;> intro _ <;> exact True.intro
    | actTime _ =>
        dsimp [reEmptied, ClaimLanguage.TrueAt]
        constructor
        · intro hsep
          exact False.elim (hNotLive hsep.left)
        · intro hfreeze
          exact False.elim ((Grid.not_freeze_of_obeysSeparateFuse h) hfreeze)

/-- Error-freedom below is enough for the re-emptying row above to obey the
    full rule. This is the cumulative ladder form: `finalBelow` is exactly the
    lower row's freeze, so the non-live clause is supplied by the lower row's
    refutation rather than by a new stability premise. -/
theorem reEmptied_obeys_of_errorFree
    {d : Distinction G} (h : ErrorFree G d) :
    (reEmptied d).ObeysSeparateFuse := by
  constructor
  · intro t hLive
    cases t with
    | floor =>
        cases hLive
    | actTime w =>
        dsimp [reEmptied, ClaimLanguage.TrueAt]
        have hnotIff :
            ¬ (d.language.TrueAt (Tier.actTime w) d.sideA ↔
              d.language.TrueAt (Tier.actTime w) d.sideB) := by
          intro hiff
          exact h.left (Tier.actTime w) ⟨hLive, hiff⟩
        have hsep : d.Separated (Tier.actTime w) := ⟨hLive, hnotIff⟩
        intro hiff
        exact h.right (hiff.mp hsep)
  · intro t hNotLive
    cases t with
    | floor =>
        dsimp [reEmptied, ClaimLanguage.TrueAt]
        constructor <;> intro _ <;> exact True.intro
    | actTime _ =>
        dsimp [reEmptied, ClaimLanguage.TrueAt]
        constructor
        · intro hsep
          exact False.elim (hNotLive hsep.left)
        · intro hfreeze
          exact False.elim (h.right hfreeze)

theorem ladder_obeys {d : Distinction G} (h : d.ObeysSeparateFuse) :
    ∀ n, (ladder d n).ObeysSeparateFuse := by
  intro n
  induction n with
  | zero =>
      exact h
  | succ _ ih =>
      exact reEmptied_obeysSeparateFuse (G := G) ih

/-- Once a seed is error-free, every positive ladder level obeys without a
    separate obedience hypothesis at level zero. -/
theorem ladder_obeys_of_errorFree
    {d : Distinction G} (h : ErrorFree G d) :
    ∀ n, (ladder d (n + 1)).ObeysSeparateFuse := by
  intro n
  induction n with
  | zero =>
      exact reEmptied_obeys_of_errorFree (G := G) h
  | succ _ ih =>
      exact reEmptied_obeysSeparateFuse (G := G) ih

theorem ladder_errorFree_of_errorFree
    {d : Distinction G} (h : ErrorFree G d) :
    ∀ n, ErrorFree G (ladder d (n + 1)) := by
  intro n
  exact Grid.errorFree_of_obeys G (ladder_obeys_of_errorFree (G := G) h n)

theorem no_level_final {d : Distinction G} (h : d.ObeysSeparateFuse) :
    ∀ n, ¬ (ladder d n).Freeze := by
  intro n
  exact Grid.not_freeze_of_obeysSeparateFuse (ladder_obeys (G := G) h n)

/-- Emptiness-sickness has no final level to name: with an error-free seed,
    neither level zero nor any positive re-emptying level can freeze. -/
theorem no_final_level {d : Distinction G} (h : ErrorFree G d) :
    ¬ ∃ n, (ladder d n).Freeze := by
  rintro ⟨n, hfreeze⟩
  cases n with
  | zero =>
      exact h.right hfreeze
  | succ n =>
      exact (Grid.not_freeze_of_obeysSeparateFuse
        (ladder_obeys_of_errorFree (G := G) h n)) hfreeze

theorem ladder_collapse_self_refuting
    {d : Distinction G} (h : d.ObeysSeparateFuse) :
    ∀ n t, ¬ (ladder d n).Collapse t := by
  intro n t
  exact Grid.not_collapse_of_obeysSeparateFuse (ladder_obeys (G := G) h n) t

def beingsLadder (G : Grid Contrib) : Nat → Distinction G :=
  ladder (beingsRow G)

def beforeAfterLadder (G : Grid Contrib) : Nat → Distinction G :=
  ladder (beforeAfterRow G)

def gridLensLadder (G : Grid Contrib) : Nat → Distinction G :=
  ladder (gridLensRow G)

def contentBeingsLadder (G : Grid Contrib) : Nat → Distinction G :=
  ladder (contentBeingsRow G)

theorem beingsLadder_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    ∀ n, (beingsLadder G n).ObeysSeparateFuse :=
  ladder_obeys (G := G) (beingsRow_obeys G)

theorem beingsLadder_obeys_succ :
    ∀ n, (beingsLadder G (n + 1)).ObeysSeparateFuse :=
  ladder_obeys_of_errorFree (G := G) (rowOf_errorFree G (.layer .beings))

theorem beingsLadder_no_level_final :
    ∀ n, ¬ (beingsLadder G n).Freeze := by
  intro n
  cases n with
  | zero =>
      exact beingsRow_not_freeze G
  | succ n =>
      exact Grid.not_freeze_of_obeysSeparateFuse (beingsLadder_obeys_succ G n)

theorem beforeAfterLadder_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    ∀ n, (beforeAfterLadder G n).ObeysSeparateFuse :=
  ladder_obeys (G := G) (beforeAfterRow_obeys G)

theorem beforeAfterLadder_obeys_succ :
    ∀ n, (beforeAfterLadder G (n + 1)).ObeysSeparateFuse :=
  ladder_obeys_of_errorFree (G := G) (rowOf_errorFree G (.layer .directedTime))

theorem beforeAfterLadder_no_level_final :
    ∀ n, ¬ (beforeAfterLadder G n).Freeze := by
  intro n
  cases n with
  | zero =>
      exact beforeAfterRow_not_freeze G
  | succ n =>
      exact Grid.not_freeze_of_obeysSeparateFuse (beforeAfterLadder_obeys_succ G n)

theorem gridLensLadder_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    ∀ n, (gridLensLadder G n).ObeysSeparateFuse :=
  ladder_obeys (G := G) (gridLensRow_obeys G)

theorem gridLensLadder_obeys_succ :
    ∀ n, (gridLensLadder G (n + 1)).ObeysSeparateFuse :=
  ladder_obeys_of_errorFree (G := G) (rowOf_errorFree G (.layer .gridLens))

theorem gridLensLadder_no_level_final :
    ∀ n, ¬ (gridLensLadder G n).Freeze := by
  intro n
  cases n with
  | zero =>
      exact gridLensRow_not_freeze G
  | succ n =>
      exact Grid.not_freeze_of_obeysSeparateFuse (gridLensLadder_obeys_succ G n)

theorem contentBeingsLadder_obeys_of_being
    (h : ∃ b : G.Being, ¬ G.Stone b) :
    ∀ n, (contentBeingsLadder G n).ObeysSeparateFuse :=
  ladder_obeys (G := G) (contentBeingsRow_obeys_of_being G h)

theorem contentBeingsLadder_no_level_final_of_being
    (h : ∃ b : G.Being, ¬ G.Stone b) :
    ∀ n, ¬ (contentBeingsLadder G n).Freeze :=
  no_level_final (G := G) (contentBeingsRow_obeys_of_being G h)

end GridConvention
end BeingConvention
end DirectedConvention

end Grid

/-- In the clock model, share-zero does not mean function-zero: the adaptive
    clock answers the present-listener call at bottom share while remaining
    non-stone. -/
theorem shareZero_not_functionZero_witness :
    AtBot (clockGrid.share ⟨Clock.adaptive, Listener.present, Chime.chime⟩) ∧
      ¬ clockGrid.Stone Clock.adaptive :=
  ⟨clockGrid.atBot_of_terminus_response adaptive_is_terminus rfl,
    adaptive_not_stone⟩

/-- In the register clock, a live share-drop rung is not yet the pole. -/
theorem rung_not_pole_witness :
    ∃ before : Config Nat, ∃ received : registerClockGrid.Weld,
      registerClockGrid.Actual received ∧
        registerClockGrid.IsShareDrop before received ∧
        ¬ AtBot (registerClockGrid.share received) := by
  refine ⟨{ tendency := 5 }, ⟨(2 : Nat), (), (3 : Nat)⟩, ?_, ?_, ?_⟩
  · rfl
  · dsimp [Grid.IsShareDrop, Grid.share, registerClockGrid]
    constructor
    · show (2 : Nat) ≤ 5
      decide
    · show ¬ (5 : Nat) ≤ 2
      decide
  · dsimp [Grid.share, registerClockGrid, AtBot, shareBot]
    show ¬ (2 : Nat) ≤ 0
    decide

/-- Assertable and displayable are different verdict voices. -/
theorem assertable_ne_displayable :
    Grid.VerdictVoice.assertable ≠ Grid.VerdictVoice.displayable := by
  intro h
  cases h

/-- A standing tendency does not determine the dated reception: in the clock
    model a live prior tendency can re-pitch to a pole-class received share. -/
theorem standing_does_not_determine_dated :
    ∃ before : Config Nat, ∃ received : clockGrid.Weld,
      ¬ AtBot before.tendency ∧
        AtBot (clockGrid.rePitch before received).tendency := by
  refine ⟨{ tendency := 5 }, ⟨Clock.adaptive, Listener.present, Chime.chime⟩,
    ?_, ?_⟩
  · dsimp [AtBot, shareBot]
    show ¬ (5 : Nat) ≤ 0
    decide
  · exact clockGrid.rePitch_tendency_atBot_of_terminus_response
      { tendency := 5 } adaptive_is_terminus rfl

/-- The pole-validating act-time is inhabited by a non-stone terminus response
    in the clock model; the validating disjunct is not merely the vacuous stone
    side. -/
theorem pole_tier_buddha_inhabited :
    ∃ w : clockGrid.Weld,
      clockGrid.Actual w ∧ AtBot (clockGrid.share w) ∧
        clockGrid.AtPoleClass w.agent ∧ ¬ clockGrid.Stone w.agent := by
  refine ⟨⟨Clock.adaptive, Listener.present, Chime.chime⟩, rfl, ?_, ?_, ?_⟩
  · exact clockGrid.atBot_of_terminus_response adaptive_is_terminus rfl
  · exact clockGrid.atPoleClass_of_terminus Clock.adaptive adaptive_is_terminus
  · exact adaptive_not_stone


end WAA
